### ISSUE TITLE
TST: SDSS remote data not found (404), failing 6 tests

### ISSUE THREAD

**Issue by pllim** [astropy/specutils#1135]
Example log: https://github.com/astropy/specutils/actions/runs/8994189000/job/24707287554

```
FAILED ../../specutils/tests/test_loaders.py::test_sdss_spspec - urllib.error.HTTPError: HTTP Error 404: Not Found
FAILED ../../specutils/tests/test_loaders.py::test_sdss_spspec_stream - urllib.error.HTTPError: HTTP Error 404: Not Found
FAILED ../../specutils/tests/test_loaders.py::test_sdss_compressed[gzip] - urllib.error.HTTPError: HTTP Error 404: Not Found
FAILED ../../specutils/tests/test_loaders.py::test_sdss_compressed[bzip2] - urllib.error.HTTPError: HTTP Error 404: Not Found
FAILED ../../specutils/tests/test_loaders.py::test_sdss_compressed[xz] - urllib.error.HTTPError: HTTP Error 404: Not Found
FAILED ../../specutils/tests/test_loaders.py::test_sdss_spplate - urllib.error.HTTPError: HTTP Error 404: Not Found
```

1. Ask SDSS if this is temporary.
2. If not, find replacement data or create fake local data to mimic the desired format.

**Comment by eteq** [comment]
I don't have any insider knowledge from SDSS, but I know this server goes up and down some of the time - not the first time this particular source of data has been 404ing.  (But the last time I remember this happening it was down for a while, like days or maybe even weeks until someone realized it...)

**Comment by pllim** [comment]
Is there a more stable source?

**Comment by eteq** [comment]
I have a vague memory of a "better" URL that essentially goes for the same place but sometimes falls back on something else?  But I don't remember much more than that.  Maybe @weaverba137 or @havok2063  have insight here (I could be just imagining this, but I think one of them might have been the person to tell me this)?

**Comment by eteq** [comment]
Oh, wait, I think I found part of it - the suggested solution was to use the SAS server: https://dr17.sdss.org/optical/spectrum/search - the problem was that it doesn't expose exactly the same data, and I think we couldn't figure out exactly how to get the same spectra.  So the test would have to be re-written for a different file (which is not impossible but is non-trivial work)

**Comment by weaverba137** [comment]
I believe a simple http-> https replacement will fix issues with das.sdss.org.

**Comment by eteq** [comment]
It looks like the das server is back up as of right sometime in the last ~ hour... but the http -> https shift is probably a good idea anyway! 

> but spSpec files I don't think exist anymore. At least I can't find any reference. I think they are now just spec files.

I wonder if that means we should just grab that one example file and  host it somewhere else? I don't think we want to deprecate the reader itself because there's still plenty of these files out there for various science use cases, but if they're not "officially" being served, we shouldn't have the tests depend on that as the authoritative copy.

**Comment by pllim** [comment]
Thanks! I confirmed locally that just upgrading to HTTPS works, so I opened https://github.com/astropy/specutils/pull/1136
