### ISSUE TITLE
Is the default implementation in`specutils.utils.wcs_utils.air_to_vac` incorrect?

### ISSUE THREAD

**Issue by andycasey** [astropy/specutils#1162]
Hi folks,

I make a lot of model/data comparisons where model spectra are in vacuum and data are in wavelengths.

Today I noticed that the default method in specutils (`scheme='inversion', method='Griesen2006'`) for converting air wavelengths to vacuum seems to be either incorrect, or inaccurate. 

I attach a figure showing a ESO/HARPS spectrum of alpha Cen A, where the ESO/HARPS spectrum is recorded in air wavelengths. In the top panel I compare the data (in air wavelengths) with some approximate spectral model (in vacuum wavelengths) in pink. The subsequent panels also show the model in pink, but the data are shifted to vacuum wavelengths using different arguments in `specutils.utils.wcs_utils.air_to_vac`. I have added a small y-offset so we can see the conversion using different methods.

![specutils-air-to-vac-issue](https://github.com/user-attachments/assets/ba6ca0b9-bba7-4dff-bcf1-b11258586c17)

You can see that in either scheme (inversion/iteration), the Greisen 2006 conversion is vastly different from all other methods. This seems to be inaccurate or incorrect, and the unfortunately the Greisen 2006 method is the default in `specutils.utils.wcs_utils.air_to_vac`. The docstring for `air_to_vac` says that 'Griesen et al. (2006) report that the error in naively inverting is less than 10^-9.'. The difference in the figure between Greisen 2006 and the other methods is about 0.07 Angstroms.. far higher than 10^-9!

I haven't cross-checked the equations in the Greisen 2006 paper to see whether the implementation in `specutils` is correct or not. I wanted to open this issue for discussion first, particularly since users will get the wrong result by using the default parameters, and debugging air/vacuum issues with noisy RV/BERV shifts can be fiddly!

**Comment by andycasey** [comment]
A note from the [International Association of Geodesy rendus](https://iugg.org/wp-content/uploads/2022/10/IUGG_GA_1999_Comptes_Rendus.pdf) (page 120), which is where the formula that Greisen et al. 2006 uses, is that the 0.25 ppm accuracy is quoted for wavelengths between 650 nm and 850 nm. 

I'd be a little surprised if it was so inaccurate outside of that range and it gets adopted as the standard, but I can't see any obvious error in the `specutils` implementation of the equation.

I tried computing the vacuum wavelengths myself using the calculation for group refractivity (instead of phase refractivity) thinking that the equations might be mixed up, and there is a difference of about 0.07 Angstroms in my example, but it goes in the wrong way (e.g., it makes the 'Greisen' wavelengths 0.14 Angstroms away from all other methods).

Unless I have made some silly mistake here, I think the default scheme or method for `air_to_vac` should be changed.

**Comment by rosteen** [comment]
Thanks for the detailed report - I'm hoping I'll have some time to look into this/think about it next week.

**Comment by weaverba137** [comment]
I did some work on this a long time ago [this notebook](https://github.com/weaverba137/pydl/blob/main/docs/notebooks/Vacuum%20Wavelength%20Conversions.ipynb) has some code and plots.

**Comment by andycasey** [comment]
Thanks for the write-up @weaverba137! I'm glad to know that someone else has encountered the same behaviour.

The equations in the Greisen 2006 paper actually go back to the 90's: Ciddor and Hill (1999), and Ciddor et al. (1996).

I found a few papers referring to errors in those papers (e.g., https://opg.optica.org/ao/fulltext.cfm?uri=ao-59-31-9771&id=441874), but all of those papers are published in Optica, which for some reason, my poor university does not have a subscription with.

**Comment by rosteen** [comment]
Ok, after some investigating, I think I at least understand why `Griesen2006` is the default method in `specutils` despite giving slightly different results from the rest of the methods. Using some of the notebook code from @weaverba137 , I generated the following plot:

<img width="762" alt="Screenshot 2024-09-19 at 12 52 24 PM" src="https://github.com/user-attachments/assets/9248edc6-4c05-4123-bf15-f5adc5232f31">

You can see from the plot (and by looking at the code) that the other methods all have wavelengths in the ~100-200 nm range where the solutions for the refraction index blow up. I suspect that `Griesen2006` was chosen because it's the only one that (at least as coded in `specutils`) is well behaved over the whole range of wavelengths I show in the plot - any of the others would give bad results for anyone working in the FUV. `Edlen1953` for example has a singularity at ~156 nm:

`refr = 6.4328e-5 + 2.94981e-2 / (146 - sigma2) + 2.5540e-4 / (41 - sigma2)`

So, the question is what the path forward is. My inclination is that we could change the default to one of the other methods, and raise an error telling the user that they need to pick another method if any of the input wavelengths are below some wavelength threshold.

**Comment by aragilar** [comment]
Just saw the message on the astropy slack. It looks like many of the galaxy redshift surveys use Morton (1991, ApJS, 77, 119) (see https://classic.sdss.org/dr7/products/spectra/vacwavelength.php, which is also used in autoz and marz, I don't recall what runz uses).

**Comment by rosteen** [comment]
@andycasey Is it alright with you if I add your plot to a section in the narrative docs?

**Comment by rosteen** [comment]
Thanks, I think the version here is fine - I included it in https://github.com/astropy/specutils/pull/1175, you can see the built docs [here](https://specutils--1175.org.readthedocs.build/en/1175/wcs_utils.html). I also set it up so that the API docs actually build for these functions now and are linked from that page.
