### ISSUE TITLE
Verify splice implementation uses bin centers and not bin edges

### ISSUE THREAD

**Issue by nmearl** [astropy/specutils#173]
The original c code implementation of splice performs a half pixel shift because the operation is performed at the bin edges, and then the resultant spectrum is shifted back to ensure that the flux value represents the value at the center of the wavelength bin.

This can be verified by checking that some absorption point exists in the center or the edge of a particular wavelength bin after the operation has been performed.

**Comment by SaOgaz** [comment]
Quote from the splice help file is as follows:
"The wavelengths in the input and output tables are given at pixel centers, and the wavelengths are typically not uniformly spaced. 'splice' must therefore compute wavelengths at the pixel edges in order to determine the limits of each bin, then accumulate flux into bins, then convert the output wavelengths back to wavelengths at the pixel centers.  The method used for computing wavelengths at pixel edges is as follows. If wl[i] and wl[i+1] are wavlengths at pixel centers, the pixel edge between them is taken to be (wl[i] + wl[i+1]) / 2. The left edge of the first pixel is wl[1] - (wl[2] - wl[1]) / 2 with a similar expression for right edge of the last pixel."

**Comment by SaOgaz** [comment]
I think given the new implementation for resample that we can close this. Do you agree @nmearl? I do have a unit test that verifies resampling that's run with the same input and output spectral axis produces unchanged flux values after running through the algorithm.  Is this enough to cover this situation, or is there an additional unit test we should add?
