### ISSUE TITLE
Smoothing functionality

### ISSUE THREAD

**Issue by brechmos-stsci** [astropy/specutils#194]
Add in smoothing functionality on the Spectrum1D object.  This will should include multiple kernels and leverage the astropy models etc.

(specviz will use this for its smoothing)

**Comment by eteq** [comment]
One side-effect of `d` that just occurred to me though: I'm not sure whether flux-conserving smoothing can be fully expressed by a choice of kernel.  (Or at least, that's not how people generally thing about it.)  I still think that means `d` is the way to go, but there might have to be a second function for that purpose, or a special keyword.

**Comment by brechmos-stsci** [comment]
> On the actual smoothing function, though: I'd like to riff on c by offering a d: s2 = specutils.processing.smooth(s1, kernel). kernel would then be one of the kernel objects that astropy.convolution supports (http://docs.astropy.org/en/stable/convolution/kernels.html). The advantage of that is that the same function can do both analytic kernels (like gaussians) and discrete kernels (which are less commonly used in optical, but are heavily used in e.g. radio).

That *is* how I am implementing it :)...
```
def smooth(s1, kernel):
    # smoothing stuff

def gaussian_smooth(s1, width):
    g1 =astropy.gaussian(width)
    return smooth(s1, g1)
```
So there is the general and the specific are just calling the general.

Perfect. I'll mock up tomorrow and create a PR.

**Comment by brechmos-stsci** [comment]
re the flux conserving. My feeling is that this whole process can be iterative.  Let's get some basic smoothing in there. Then, when needed (or "next") I can tackle flux conserving etc.  I can create a ticket for that too if you want.

**Comment by nmearl** [comment]
> That is how I am implementing it :)...

I think Erik is getting at the case where the kernel function (e.g. `Gaussian1DKernel` astropy object) is initialized and passed in _by the user_ to the smooth function, instead of an explicit kernel-specific function being defined. The smoothing function would then be responsible for convolving the spectrum with the user-supplied kernel and returning e.g. a new `Spectrum1D` object (or altering the provided one in-place).

**Comment by nmearl** [comment]
This is for instance how [photutils does filtering](https://photutils.readthedocs.io/en/stable/api/photutils.utils.filter_data.html?highlight=kernel), for example.

**Comment by brechmos-stsci** [comment]
Is there a preferred way of doing a deep copy of a Spectrum1D object?  In the not-in-place smoothing, I would like to create a copy of the spectrum passed in.  Best would be `s2 = s1.copy()`, or similar, but I don't see the method.  I can do `s2  = copy.deepcopy(s1)`, is that preferred or am I not seeing the deep copy method?

Second question... I need to set the flux values in either case (to the smoothed flux values).  I don't see a flux setter, is that by design? Or is that something I can add? 

@eteq @nmearl

**Comment by nmearl** [comment]
Hmm, I we don't have a copy mechanic built in. My main concern would be the WCS information, and it looks like FITSWCS _does_ use deepcopy internally. Since GWCS is picklable, I'm going to assume there's no issues doing a deepcopy there either.

I'd say deepcopy is the way to go for now. Not having a flux setter is by design. In initial conversations, specutils operations are supposed to by default return new objects instead of editing in place. To edit the data you're need to set the `_data` attribute, not the `flux` attribute, since the `flux` property creates a quantity from the passed-in data and unit information.

**Comment by brechmos-stsci** [comment]
kk.  @eteq had suggested doing in-place, but if Spectrum1D is not designed that way, I'll remove that possibility.  If Spectrum1D design changes later on it will be easy to add back in.
