### ISSUE TITLE
Line-fitting from line lists

### ISSUE THREAD

**Issue by brechmos-stsci** [astropy/specutils#195]
Add line fitting functionality based on line lists. 

(this will be used by specviz)

**Comment by SaOgaz** [comment]
@brechmos-stsci, shouldn't this be referenced in some your recent PRs?

**Comment by eteq** [comment]
I'm going to make a command decision to close this in favor of #247 purely because there's a bit more detail in #247.  But if anyone objects, feel free to instead re-open this, close #247 and copy my comments here

**Comment by eteq** [comment]
I re-labeled this to a more specific thing, since I think that was the original specviz context.

To say a bit more: #247 is about the "whole deal" of line lists, while I think (?) this is meant to track the more specific element of "I have a list of possible lines, check if those actually have a line", which is much smaller than the gargantuan task of all possible line fitting approaches (the topic of #247).

I believe @brechmos-stsci plans to works on this as part of a larger task (although not quite as large as "everything to do with fitting lines" 😉 )

**Comment by eteq** [comment]
I'm going to close this and start over with a new issue as some of the discussion has been overtaken by other PRs
