### ISSUE TITLE
Centroid Measurements

### ISSUE THREAD

**Issue by brechmos-stsci** [astropy/specutils#236]
An estimate of the center using the first moment of the pixel intensities within the selected wavelength region. 

The region selection might be calculated previous to calling this method and therefore the centroid would be over the whole input spectrum.

**Comment by eteq** [comment]
This should use the region-definition semantics discussed in #245, but otherwise is pretty straightforward.  One thing to bear in mind: this algorithm only really works *if* the spectrum is continuum-subtracted.  I think that shouldn't be done automatically, but it *should* be stated very clearly in the docs that the continuum-subtraction needs to be done *first* (i.e. on the input spectrum), otherwise results will probably be wrong.  Should also give an example of that in the docstring  (e.g., a one-line ``center = centroid(spectrum - continuum, region)``
