### ISSUE TITLE
FWHM measurement

### ISSUE THREAD

**Issue by brechmos-stsci** [astropy/specutils#238]
Calculate the full width at half maximum of the input spectrum.

**Comment by eteq** [comment]
An important question here is "which FWHM". That is, there are different algorithms to quickly estimate FWHM that work different on different inputs.  I *think* splot uses an approach of gitting gaussian or lorentzians, and then reporting the FWHM of the corresponding fit.  I'm not sure we want to do that here, though, because it mixes together the concept of line-fitting (which requires assumptions about models, etc) with "quick-look estimates", or robust estimators.  

So I'm inclined to say this should just be syntactic sugar for ``2*sqrt(2*ln(2)) * sigma``, where ``sigma`` is whatever #241 yields... (and see further discussion there).

**Comment by nmearl** [comment]
We use a quick method in our model initializers in specviz. Likewise relevant for #241. Mainly:

```python
 # Width can be estimated by the weighted 2nd moment of the x coordinate
dx = x - np.mean(x)
fwhm = 2 * np.sqrt(np.sum((dx * dx) * y) / np.sum(y))
center = np.sum(x * y) / np.sum(y)
sigma = fwhm / 2.355

# Amplitude is derived from area
delta_x = x[1:] - x[:-1]
sum_y = np.sum(y[1:] * delta_x)
amplitude = sum_y / (sigma * np.sqrt(2 * np.pi))
```

**Comment by drdavella** [comment]
A fairly naive question on my part, but is this generally reported in terms of wavelength or frequency? Should the user pass a parameter to indicate on or the other? If so, which should be the default?

**Comment by hcferguson** [comment]
It's clearest to return it in the same units as the spectrum. However, physically, it generally makes more sense in velocity. There is a quick summary of the physics giving rise to  different relevant spectral-line profiles in [these slides](http://www-star.st-and.ac.uk/~kw25/teaching/nebulae/lecture08_linewidths.pdf). Neither the Lorentz profile nor the Voigt profile actually have well-defined moments, so using Gaussian moments as a guess may be a bit dangerous. But it seems pretty common to do it. 

I think it would be great to have a  specutils tutorial on measuring line widths (or shapes in general), starting from the quick & dirty and working up in increasing complexity.

**Comment by hcferguson** [comment]
BTW...Wikipedia suggests using using a median and interquartile range as a more robust estimator for the Lorentz distribution. Or the truncated mean of the middle 24% of the sample.

**Comment by hcferguson** [comment]
Even in the quick & dirty calculation, one usually wants to define the continuum level, and that usually means defining an ROI or two for the continuum and a method of estimating and interpolating.

**Comment by brechmos-stsci** [comment]
I would suggest that the current "simple" version be put in and then these could be the next round of changes. It might be easier, too, to make this change when the analysis framework is implemented too (class based rather than method based).

**Comment by hcferguson** [comment]
Agreed.
