### ISSUE TITLE
Gaussian width (sigma)

### ISSUE THREAD

**Issue by brechmos-stsci** [astropy/specutils#241]
1-sigma full width of an equivalent Gaussian (Can be determined from moments or fitting). splot has some algorithms. 

This might be overtaken or use some work in the spectral fitting as it will likely use spectral fitting (which uses the astropy.modeling work).

**Comment by eteq** [comment]
As I mentioned in #238, I'm inclined to say this function should be a "quick" method, rather than a "do the whole line-fitting business" (which I *think* is what splot does now that I look at it).  That is, this could be a *second moment* analysis, given a region.  That's a very fast algorithm that provides a reasonable guess to start from.  If so the function should probably be called something a bit more specific like ``moment_sigma`` (and then #238 would probably be ``moment_fwhm``?)

**Comment by drdavella** [comment]
Just to be clear: this should return `approx_sigma * 2`, not `approx_sigma`, correct?
And #238 should return `approx_sigma * gaussian_sigma_to_fwhm`?

For reference, for now the `approx_sigma` calculation would come from @nmearl's proposed quick-and-dirty solution in #238.

cc @eteq

**Comment by eteq** [comment]
Note some relevant discussion in #281 - this is about an "estimator" of the FWHM, as opposed to the FWHM itself (I guess I should have answered https://github.com/astropy/specutils/issues/241#issuecomment-413971323 above).
