### ISSUE TITLE
Spectral cross-correlation (as a RV/redshift measurement tool)

### ISSUE THREAD

**Issue by SaOgaz** [astropy/specutils#257]
original card by @keflavich

**Comment by eteq** [comment]
Elaborating further on this: this issue is about implementing an analysis function (although probably as a class, as described more in #266) that determines the best-fitting redshift given an observed spectrum and a template spectrum.  The scope of this is very large because there's a *lot* of prior art on this topic.  But I think the goal for this issue specifically is a bit more narrow: implement a cross-correlation tool that does the *fundamental* cross-correlation operations, and then we can later expand it to have additional bells and whistles.

**Comment by eteq** [comment]
There are two possible ways to start this (both we probably want to implement eventually, but I'm not sure which is the best to start with), which mainly have performance-accuracy tradeoffs:

1. A true cross-correlation analysis - this is basically implementing the IRAF task http://iraf.noao.edu/projects/rv/rv.html - the advantage with this approach is that it's very fast because it can be implemented in the spectral domain using fast fourier transforms or other fast cross-correlation tools (all of which are basically already implemented in `scipy` or `numpy` and just require some bookeeping in `specutrils`).  The down side is that it requires resampling the spectrum onto a grid that is compatible with fourier transforms (i.e. ), and resampling data always means some level of accuracy loss.
2. Cross correlation in the sense of trying to fit the template to the observed spectrum (or vice versa) and optimizing on the chi-squared statistic - basically #256 but with the redshift as a free parameter rather than choice of model. At least with naive implementations this is probably a lot slower than 1, but is probably more straightforward to implement - it is basically #487 combined with a scipy fitter to optimize on the redshift (caveat: we currently do not have a way to do redshifting - #422 should provide that, but in the meantime this could be implemented with the redshifting done "manually" - i.e., just muliplying the spectral axis by 1+z and making a new spectrum with that as the spectral axis)

**Comment by camipacifici** [comment]
There are two potential science cases.
Science case 1: the user wants to fit the redshift and at the same time visually inspect the result.
Science case 2: the user has a large number of spectra and wants to get redshifts for all of them and inspect at a later time.

The plan is to first build the cross-correlation function from the IRAF task (http://iraf.noao.edu/projects/rv/rv.html or http://tdc-www.harvard.edu/iraf/rvsao/xcsao/xcsao.html) or directly from Tonry & Davis (1979). Observed and template spectra would be "prepared" separately (resample, continuum subtraction, masked emission lines) and whether to include the preparation in the function or not will be decided later.

**Comment by ibusko** [comment]
@eteq @camipacifici 

I have an initial version of a workflow notebook in a branch in my fork: https://github.com/ibusko/specutils/tree/redshift-crosscorr-workflow

The notebook, Workflow.ipynb, is at the top level directory, together with a few spectrum files for testing. I used the notebook  with a couple of different types of data: synthetic data (Gaussian + continuum), the SDSS test spectrum, and a couple of synphot templates (used both as observation and template).

**Comment by ibusko** [comment]
@eteq @camipacifici

Following discussion with @camipacifici, I fixed and replaced the previous notebook with two almost identical notebooks with the cross corr workflow. Workflow_1 uses synthetic data, and Workflow_2 uses the SDSS spectrum and a Bruzual-Charlot template. 

@camipacifici I traced the slightly off-values for redshift to the use (or lack thereof) of the 'rest_value' wavelength associated to the input spectrum. When we refer the redshift calculations to that value, the correlation peak sits at exactly the expected value (within 6 decimal places for the noiseless synthetic data).

**Comment by ibusko** [comment]
@eteq @camipacifici

Regarding the Workflow_X notebooks above, you'll notice that the `template_correlation` function returns a `lag` array with the correlation lags. When developing that function, I made that array to be expressed in velocity units. For which the function then requires that the input spectrum contains a valid value for its `rest_value` attribute. 

But thinking about that now, I realize that it's perhaps a too restrictive requirement. Maybe we should have the `template_correlation` function more flexible?

I thought that at least four possible API choices could be provided. Such as:
- the user provides a plain spectrum with no `rest_value` defined, nor provides anything in the guise of calling parameters. In this case, the function returns the lags expressed in delta wave, in units of wavelength.
- the user provides a plain spectrum with no `rest_value` defined, but provides a rest value via function call. In this case, the function returns the lags expressed in velocity, defined based on the rest value provided.
- the user provides a spectrum with `rest_value` defined, but does not pass anything as function parameter. In this case, the function returns the lags expressed in velocity, defined based on the rest value defined in the spectrum.
- the fourth option would be to have a rest value passed as call parameter, to override whatever is set in the spectrum.

What you think? Are there any user scenarios that would benefit from such API?

**Comment by ibusko** [comment]
Added a 3rd notebook, Workflow_3.ipynb

**Comment by nmearl** [comment]
Implemented and merged in #544.
