### ISSUE TITLE
Extinction models (wrap or reference http://dust-extinction.readthedocs.io/en/latest/)

### ISSUE THREAD

**Issue by SaOgaz** [astropy/specutils#260]
Original card by @keflavich

**Comment by eteq** [comment]
As an update from when this was originally written: the functionality for this is now in `dust_extinction` - https://dust-extinction.readthedocs.io/en/latest/dust_extinction/extinguish.html has an example of this using just the flux, but it *should* already work by just replacing `flux` in those examples with a `Spectrum1D` and `wavelength` to `spec.wavelength`.

However, that's awkward because it requires double-using the spectrum.  Also for attenuation it's more complicated because the flux may be relevant in more ways than a multiplicative scaling.  So that argues for a wrapper more like `new_spec = extinguish_spectrum(spec, ext)` or  something like that.  It may be more logical to put that wrapper in `dust_extinction`, in which case this issue turns to *documenting* in `specutils` that the user should look there for extinction, but that should be discussed with @karllark (maintainer of `dust_extinction`).

cc @camipacifici @PatrickOgle

**Comment by karllark** [comment]
I am interested in exploring what it would take to add such a wrapper in dust_extinction.  I'm not that  familiar with specutils, but am interested in learning.

**Comment by PatrickOgle** [comment]
@eteq @karllark 
So has it been decided that this will go in astropy.dust_extinction rather than astropy.specutils?
If so, I will create a Jira issue for specutils documentation pointing to dust_extinction.

**Comment by nmearl** [comment]
Documentation concerning using the `dust_extinction` package in specutils has been added in #598. Further discussion about adding wrappers to the `dust_extinction` package should happen in issues opened there.
