### ISSUE TITLE
Consistent style of API for analysis and manipulation tools

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#266]
The proximate cause of this is discussion is design considerations for several features (#224, #228, #255), particularly an in-person discussion related to #255 (involving @hcferguson @SaOgaz @crawfordsm and myself).  But it leads to a broader item: we should provide a consistent way of implementing/exposing the API the analysis and manipulation tools so that users and devs don't get interface whiplash (a la the matplotlib functional/OOP divide).  While there have been a few separate in-person discussions about this with various parties, the goal of this issue is to summarize the logic/decisions at the high-level so that it can be seen by all.

While at the basic level this is a functional vs object-oriented question, there's some `specutils`-specific considerations. These include:
* The need to support multiple algorithms for what seems to be the same thing but where they have different physical interpretations and therefore different science results (e.g. https://github.com/astropy/specutils/issues/255#issuecomment-409686415)
* Several operations that require "weights" - both in the sense of per-spectrum weights and per-pixel weights. Those weights *often* are, but are not *always* encoded in the uncertainty.  But they only make sense for a *specific* operation (not the spectrum as a whole)
* Many operations have several options/parameters that affect how they operate

I think the options are better when put out as actual pseudo-code examples.  So here are wait I see as the key 5 competing options (although of course others could add more):

1. (purely functional, each algorithm its own function): ``result_or_new_spectrum = operation_with_algorithm1(single_or_list_of_specs, weights=weights, options=...)``
2. (purely functional, each operation its own function): ``result_or_new_spectrum = operation(single_or_list_of_specs, weights=weights, algorithm='name_of_algorithm', options=...)``
3. (object-oriented, each algorithm its own class): 
```
op = OperationWithAlgorithm1(options=...)
result_or_new_spectrum = op(single_or_list_of_specs, weights)
```
4. (object-oriented, each operation its own class, data stored in operation) - similar to the `ccdproc` combiner classes: 
```
op = Operation(single_or_list_of_specs, weights)
result_or_new_spectrum = op.do_algorithm1(options=...)
```
5. (operations/algorithms live as *methods* of the collection objects): 
```
specc = SpectrumCollection(...)
result_or_new_spectrum.operation_with_algorithm1(weights, options=...)
```

One thing to note: it's pretty straightforward to wrap the 3/4 (or 5, although that's a bit harder) in functions to present them to *users* as 1/2, even though the implementation is 3/4/5. I think we should *start* without such "wrapping", and then add wrappers later only if users find our first try too difficult/un-desirable.

Another API convention that I think is less controversial but worth noting for context: I think is good to do nonetheless: any time multiple spectra are inputs or outputs, they should be passed as either `Spectrum1D` with multi-dimensional `flux` or`SpectrumCollection` if possible, or a list of `Spectrum1D`'s (if there is no regular grid and therefore `SpectrumCollection` is pointless).

cc @hcferguson @crawfordsm @SaOgaz @nmearl @keflavich @brechmos-stsci

**Comment by eteq** [comment]
Now with that as intro: my preferences from favorite to least favorite: 3, 1, 2, 5, 4 .  I favor 3/1 in general because it's the most explicit for the user: they know *exactly* what algorithm they're using because it's in the name.  I prefer 3 over 1 because it makes it easier to say "I want to use this algorithm" and pass it into a pipeline, allowing analysis of multiple spectra the same way without needing to pass through the same keywords all the time.  (I can give why I less-favor 2,5,4 in that order as needed if the discussion evolves.)

Note one thing that's not in the above API discussion *but* I think is good to do nonetheless: any time multiple spectra are inputs or outputs, they should be passed as either `Spectrum1D` with multi-dimensional `flux` or`SpectrumCollection` if possible, or a list of `Spectrum1D`'s (if there is no regular grid and therefore `SpectrumCollection` is pointless).

**Comment by hcferguson** [comment]
I leaned toward 5 in the meeting, but on reflection I think that would be an impediment to having users contribute algorithms, and also make the collection objects too cumbersome. 

I lean towards 3 as being similar to Astropy models and scipy.stats. In both cases, it's pretty easy for users to add their own, building on top of the base class, and therefore not have to deal with issues that are in common between algorithms. 

I think 1 & 2 lead to more code duplication. Or basically hiding the class under a functional interface -- which means we should do 3 or 4 first anyway. 4 seems less natural to me than 3, and maybe a bit less easily extensible. Adding an algorithm requires adding a new unique method to the class instead of subclassing and overloading the algorithm methods with your own algorithm. 

In all cases, I think it behooves us to think of an easy way for people to save their options. Maybe we punt and say: work in a Jupyter notebook or write a script if you want to be able to save your work, but I do think that is punting a bit. This is a larger issue than for SpecUtils, since the same mechanism ought be used throughout the Astropy ecosystem. Anyway, I just mention it in this context because I think it favors the class approach as well, since down the road it will be easier to add a common "output my state" method.

**Comment by SaOgaz** [comment]
I think i'm in agreement with most of the comments here.  I feel that 4 is overly complicated, especially for newer users, and that 5 is overloading/overdoing what types of methods should be placed in the `SpectralCollections` object. 

I like 1 and 3 the most.  1 seems to me the most simple representation (especially from the users perspective), and would make things easy to find.  But I can see Harry's point about code duplication.  And although 3 is slightly more complicated then 1 I think the gains make up for the extra "complication". Harry also brings up the good point that this is how certain parts of Astropy already work.  And my personal experience (as well as what I've heard from other less experienced users) is that 3 (for it's Astropy instances) has been pretty easy to pick up and learn how to use when there are clear documented examples of usage.

**Comment by brechmos-stsci** [comment]
I personally like 3 where the algorithm rolled into a class.

But maybe I am mis-understanding what it means. @hcferguson, I am not seeing how `scipy.stats` follows the convention in 3.  I do see `astropy.modeling.models`.

So, SNR for 3 would be implemented something like:

```
class Analysis:
    def __init__(self):
        pass

    def prepare_inputs(self):
        # do some checking of input spectra (flux exists blah blah)

    def calculate(self):
        # 

    def __call__(self, spectra):
         prepare_inputs(self, spectra)
         calculate(self, spectra)            
         etc

class SNR(Analysis):
    def __init__(self):
        pass

    def prepare_inputs(self):
        # check flux
        # check uncertainties exist

    def calculate(self):
        return mean(spectra.flux / spectra.uncertainty)
```

Is that the basic idea?

**Comment by hcferguson** [comment]
@brechmos-stsci That's the basic idea. One downside is that it implies two steps for doing the operation: instantiate the class, and then call it. I'm not wildly fond of ```__call__``` as the paradigm for doing this because I think it obfuscates that there can be multiple methods associated with the class. But it does save typing, and when the base class is really intended to do only one thing, maybe that's fine.

In the case of something as straightforward (and common) as SNR, we might want to make this more convenient, so you can instantiate and evaluate in one step. I think it's a straightforward extension to add such one-liner convenience, either by building a functional wrapper or maybe using @classmethod? 

In the case of scipy.stats, the example I was thinking of was ```rv_continuous``` as the base class. The various distributions, e.g. ```norm``` are built around this and thus don't have to rebuild the machinery for extracting for various statistical quantities or random samples. To add a new statistical distribution, just overload the ```_pdf``` or ```_cdf``` method and then all the rest of the methods are available to you. The ```__call__``` method there is one of many (and I haven't had much, ahem, call to use it).

**Comment by nmearl** [comment]
As I mention [in the comment on resampling algorithms](https://github.com/astropy/specutils/issues/255#issuecomment-408267947), I support the astropy modeling style of subclassing to implement individual algorithms (method overrides on subclasses) on operations (base class).

**Comment by eteq** [comment]
The consensus looks to be option 3 in my original list.  So we are calling the matter decided, but will leave this issue open until we conclude that all the tools *follow* this philosophy.

**Comment by astrofrog** [comment]
FWIW I agree 3 makes sense internally, but I think we'll probably find that doing this:

> One thing to note: it's pretty straightforward to wrap the 3/4 (or 5, although that's a bit harder) in functions to present them to users as 1/2, even though the implementation is 3/4/5. I think we should start without such "wrapping", and then add wrappers later only if users find our first try too difficult/un-desirable.

makes sense. As a newbie, I found it very frustrating to do things like:

```
parser = Parser()
parser.parse(filename)
```

rather than just

```
parse(filename)
```

So I agree with implementing 3, but I'm pretty sure there will be cases where a functional interface will need to be provided.

**Comment by astrofrog** [comment]
I removed my previous comment, but just wanted to say that whatever you decide on, please make sure that you involve users in terms of the final API. I wouldn't say that astropy.modeling is the easiest API in Astropy, and users can definitely be confused about the whole instantiating fitters.

I think going with 3 internally is fine for now, then write some docs, and do some user testing to see what they think of the API. I definitely don't think we'll want to end up with things like:

```
snr = SNR()
snr.compute(spectrum)
```

as the recommended API.

**Comment by drdavella** [comment]
Just a quick comment here, but I think we can/should promote code reuse without exposing a class-based interface to the user. I agree with @astrofrog that the API should be the driver here. The underlying implementation may very well end up being class based, but whether it is or not the user shouldn't have to know anything about it.

**Comment by nmearl** [comment]
We've converged on two general use cases:

1. When state is required, we take the class-based approach (option 3) in which users instantiate a parent class object and use its call method to perform the operation on provided data (e.g. resampling).

2. When state is not needed, operations are implemented as simple functions (option 2) that take `Spectrum1D`s as arguments.

This conversation has become a bit stale with all the changes since its opening. Closing now, new conversations should happen in a new issue.
