### ISSUE TITLE
Spectral_axis/wavelength property confusing after slicing

### ISSUE THREAD

**Issue by brechmos-stsci** [astropy/specutils#271]
I believe there appears to be a bug when slicing a spectrum object.  For example, if I create a spectrum as:

```
import numpy as np
import astropy.units as u
from specutils.spectra import Spectrum1D

np.random.seed(42)

spec = Spectrum1D(spectral_axis=np.arange(10) * u.AA, flux=np.random.sample(10)*u.Jy)
print(spec.spectral_axis)
print(spec.flux)
```
then the output is (expected):
```
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] Angstrom
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258] Jy
```
Now, when I slice the spectrum using the `[]` and look at the output:
```
>>> sub_spec = spec[4:8]
>>> sub_spec.spectral_axis
 <Quantity [0., 1., 2., 3.] Angstrom>
>>> sub_spec.wavelength
 <Quantity [0., 1., 2., 3.] Angstrom>
>>> sub_spec.flux
<Quantity [0.15601864, 0.15599452, 0.05808361, 0.86617615] Jy>
```

The flux sub spectrum output (bottom line) is correct, or at least expected (ie it **is** the 4-8 elements). BUT, the spectral_axis and wavelength lines (5th and 3rd last line) is not correct, or at least what I would have expected. It shows [0, 1, 2, 3] and I was expecting `[4, 5, 6, 7] Angstrom`.

The wcs appears to be copied over as I can do:
```
>>> sub_spec.wcs.world_to_pixel(np.array(1*u.AA))
1.0
```

but I don't think that helps me.

So, I think there is a bug in the slicing or at the very least it isn't clear (to me).

@eteq @nmearl @crawfordsm

**Comment by brechmos-stsci** [comment]
I discussed with @eteq offline and he confirms this is a bug.  I'll fix and create a PR

**Comment by eteq** [comment]
Note, this is partly a bug because currently `NDData` does not support generic slicing of the `wcs` (because that is hideously complicated!)  At some point in the future maybe `NDData` *will* support this.  At that time we might consider removing the fix for this (at least in the relevant Astropy versions), but that could be literally years, as a generic slicing-of-wcs solution has a *lot* of parts to get moving together.

**Comment by nmearl** [comment]
@brechmos-stsci the mixin _does_ have a `__getitem__`, more specifically, the `NDSlicingMixin` class which handles slicing the wcs, uncertainties, and the mask.

There are two issues at play here: 

1) FITS WCS should support slicing. The reason this still fails on a FITS WCS is because the `wcs` attribute on the `Spectrum1D` class is a reference to an adapter class instance, not the actual FITS WCS instance, a `spec.wcs.wcs[2:4]`, for instance, will return the appropriately sliced FITS WCS slice.

2) The GWCS class does not support slicing in the normal sense. I believe in previous discussions I've had, it's going to take an implementation on the adapter class to sort out the slicing, with the GWCS using something like the [region selector](https://gwcs.readthedocs.io/en/latest/#module-gwcs.selector).

**Comment by brechmos-stsci** [comment]
@nmearl Correct, this is why I was going to overload the `__getitem__` in order to deal with spectral_axis.  Are you suggesting the bug is not in specutils but in the `NDSlicingMixin` class?

**Comment by nmearl** [comment]
Your comment on the PR made it seem like you weren't able to find the `__getitem__` override that already exists in the `NData` hierarchy. I just wanted to point out that it's buried in the slicing mixin.

I'm suggesting that the bug is a WCS issue, not a spectrum issue. The slicing machinery in the `NData` mixin is sufficient right now and we don't need to be overriding the `__getitem__` dunder method of the `Spectrum1D` object. These two slicing issues should be dealt with in the WCS adapter classes in order to uniquely handle the slicing cases for each _type_ of WCS.

**Comment by eteq** [comment]
@nmearl - I'm not sure I completely follow here: I think I got the first part, which is that it makes sense for any fix on this to go in `NDSlicingMixin` instead of `Spectrum1D` - that makes sense to me now that you say it.

*However*, the Bug @brechmos-stsci points out is clearly a problem - and there's going to be no way to fix this before the next astropy release, and possibly not even then.  So I'm thinking we have to "paper over" it for now in `Specutils`.  Or did you mean you thought we should do that "papering-over" in `WCSAdapter`?  I'm against that only because I think we want to eventually replace `WCSAdapter` with the APE14-compliant interface, so we don't want to put specutils-specific functionality there if possible.

**Comment by nmearl** [comment]
Sorry, I'll try to clarify a bit. I _do not_ think we should be putting fixes in `Spectrum1D` or `NDSlicingMixin`. I _do_ think we should putting the fix in `WCSAdapter`, and then ensuring similar functionality is handled in whatever slicing machinery comes with the new APE14 interface. From what I understand, we're still going to need some type adapter that makes `FITSWCS` and `GWCS` compatible with the APE. In that case, slicing should be handled there, and be included in cases even outside specutils where users what to slice an APE14-compliant WCS object.
