### ISSUE TITLE
extract_region sometimes returns None

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#367]
As detailed further in spacetelescope/specviz#471, `extract_region` returns None for some cases where a spectral wcs is provided.  This causes crashes when (understandably) user code assumes extract_region always returns a region.

@brechmos-stsci is already looking into this based on the discussion in spacetelescope/specviz#471, so assigning him here.

**Comment by nmearl** [comment]
This seems to be due to the fact that if the `all_world2pix` transform fails, the `extract_region` appends a `None` to the spectrum list, and then return that. In the case that any region extraction fails, it ought to just return the input spectrum along with a logged error message.

**Comment by brechmos-stsci** [comment]
Ummm..  but then what would you do if `extract_regions` is called and *one* of the SpectralRegions in the input list fails?  Would you want to return an error on `extract_regions` too?  I think it is incumbent on the user of `extract_region(s)` to check the output (ie None or not).  Though, having some type of error message might be helpful.

**Comment by nmearl** [comment]
I think if a single extraction attempt fails (and the user has provided a list of potential extraction regions) _nothing_ should be appended to the list of regions, an error should be logged, and the extraction function should continue to the next region.

I suppose this is just a user experience thing. Either the `extract_regions` should _always_ return a `Spectrum1D` -- the original in the case that all extractions fail, or a combination of the regions in which the extraction succeeded -- or the `extract_regions` should return `None` when it reaches a failure.

I have a slight preference for the former, but can see where the latter would be desired (as it prevents users from assuming the operation succeeded if they neglect to look at the error message).

**Comment by eteq** [comment]
I'm confused by this: what do we mean by "fail" here?  I would have thought the only possible "failure" is to ask for a region outside the spectrum, which should yield an "empty" spectrum or something like that.

**Comment by hcferguson** [comment]
It seems okay for me for SpecUtils to raise an exception if the region goes outside the range of the spectrum. But then we should make it convenient for users to define one-sided regions that go "to the end" when they define them.

On the SpecViz side, we will need to include checking to make sure it is never passing something to SpecUtils that would go outside the range.

**Comment by brechmos-stsci** [comment]
I want to be clear about what is there right now in the code. There are two methods:

1. `extract_region` which takes a `Spectrum1D` and a `SpectralRegion` and returns a `Spectrum1D` (of the extracted region.  Currently if this fails then None is returned (which is the discussion part).

2. `extract_regions` which takes a `Spectrum1D` and a list of `SpectralRegion`s and returns a list of Spectrum1D objects

If `extract_regions` did not exist, then I get the raise exception idea.  But with `extract_regions`, let's say we pass it 10 `SpectralRegion`s and all are good except 1.  Do we want to raise an exception because of just the 1 bad one?  

I am good either way and happy to change the code.  Either way there is going to have to be extra checking in the users code who calls `extract_regions`.  Either they are going to have to catch the exception and do something with it, or they will have to check for None in the list.

**Comment by nluetzge** [comment]
Ok maybe I'm misunderstanding something here but I don't think in that specific case of spacetelescope/specviz#471 the wcs of the spectrum is *wrong*, it simply tries to apply a `world_to_pixel` with a value with a unit and that breaks it (at least that's what I think is happening) so I think there should be a change in the code that prevents it from doing it if we use the FITSWCS_adapter because I think it work with the GWCS_adapter

**Comment by brechmos-stsci** [comment]
@nluetzge and @eteq Based on the above comments here is what I will do:

1. Change `extract_region(s)` so an exception is raised if there is a problem with the WCS or any other problem with the Spectrum1D object input.
2. FIx Spectrum1D so it will accept an empty `spectral_axis` and empty `flux` as input (needed for step 3)
3. Change the output of `extract_region(s)` so an empty `Spectrum1D` object is output if the `SpectralRegion` is completely outside the bounds of the input `Spectrum1D` object.
4. Look at Nora's point about the WCS adapters and potential problem related to converting with or without units.

**Comment by brechmos-stsci** [comment]
As soon as https://github.com/astropy/specutils/pull/373 is merged, I can get back to working on this ticket.

**Comment by brechmos-stsci** [comment]
All my discussion about about `extract_regions` was for naught, there is *no such thing* as `extract_regions`, there is only `extract_region` :stuck_out_tongue_winking_eye:. It was a sub-region thing I was thinking of.  So, not relevant for much, just noting my head got confused.
