### ISSUE TITLE
JWST loader not using error/uncertainty arrays

### ISSUE THREAD

**Issue by SaOgaz** [astropy/specutils#424]
We still need to implement this.

**Comment by eteq** [comment]
One other thing to add - the JWST spectral data files have additional columns like "BACKGROUND" and "DQ".  DQ maps well onto the already-existing attribute `flags` (which NDData understands).  But some of the other columns are less obvious. 

So I propose we attach DQ to `mask` but just copy over other columns as-is.  Longer term we might need to think how to define "arrays that act like flux, but aren't the flux itself), but for now it's better to just have the data in the object if possible.

This *may* be best done as a separate issue, but I'm putting it here because it's pretty closely related so might be a decent one-off.

**Comment by nmearl** [comment]
Do we have a list of the columns provided by JWST data that we wish to keep?

**Comment by nmearl** [comment]
Closing in favor of #685 since the main topic of this issue has been addressed.
