### ISSUE TITLE
Template fitting for redshift

### ISSUE THREAD

**Issue by javerbukh** [astropy/specutils#488]
This came from a discussion during our latest sprint (July 18th) review where we were discussing the template matching ticket (#256 ). This discussion focused on what happens before template matching. As I understand it: given a group of templates, the user will want to find the redshift that creates the lowest chi square, which is then useful for the template matching code.

**Comment by eteq** [comment]
To elaborate a bit further on this and its relationship to #256 and other issues (at least as I see it):

#256 is about having a library of templates and a *known* redshift, and asking "which model is best".  #257 is about having a single model and a single spectrum and asking "what's the best-fit redshift".  As it turns out, though, in some science cases (the one I'm most familiar with being trying to find the radial velocity of a star where you do not know what type of star it is), what you really want is "find the best fit redshift for each in a library of templates, and then pick the best fit model and use that to determine the redshift". So that's basically #256 + #257.

So in the end, while we want to allow #256 and #257 to work, I think these are not actually very distinct operations: instead we want a single *implementation* that does chi-squared fitting (i.e., something like #487) and has an *option* to also adjust the redshift assumed for each model-to-observed comparison before the chi-squared selection.  Then the user sees the same interface for both problems, and selects the various options by just turning on the "find the redshift" option or not, and can even get to the basic version of #257 by passing in a *single* template.

**Comment by camipacifici** [comment]
I see usefulness in extending #256 to the case of unknown redshifts. Basically, the chi-square calculation would be computed for all the templates moved on a specified grid of redshifts. The user could call this new "template matching with unknown redshift" by inputting the observed spectrum, a list of template spectra, a redshift range where they expect the object falls, and a redshift accuracy. The downside is that this will probably be quite slow and not ideal for people who just want the redshifts of a long list of objects.

I would see #257 as a separate, much more efficient, module that would use cross-correlation to just calculate the redshifts. Something like this IRAF task http://tdc-www.harvard.edu/iraf/rvsao/xcsao/xcsao.html.

My proposal is to make this ticket about extending #487 to the case of unknown redshift and continue on #257 to build a cross-correlation module to calculate redshifts efficiently.
