### ISSUE TITLE
Docs: what does `excise` do?

### ISSUE THREAD

**Issue by keflavich** [astropy/specutils#496]
There are excise_region functions:
https://specutils.readthedocs.io/en/latest/api/specutils.manipulation.excise_regions.html#specutils.manipulation.excise_regions

that say they're using convolution.  I think the docs were incorrectly copy and pasted from something else?  I'd submit a PR, but I don't know the answer...

**Comment by dhomeier** [comment]
I've come to similar conclusions when trying to retrace the procedure `fit_lines(..., exclude_regions=[...])` is initiating in #505.
What it does is certainly replacing specified regions of the spectrum with a fill-in function provided by `exciser` - with `linear_exciser` currently the only available option. The doc strings on convolution don't seem to have anything to do with this. There were some other questions that came to my mind:

1. Is there really a need for two separate functions `excise_regions` and `excise_region`, when the former has the sole function of repeatedly calling the latter? And if there is, does it really need a full duplication of the documentation etc., instead of just marking it as a thin wrapper to `excise_region`? But since the latter is not exposed outside of this module, I would think that `excise_regions` could just as well do the call to `exciser` for each `region` directly.

2. `linear_exciser` currently returns the `uncertainty`, if present, unmodified, which is obviously no longer correct for the replaced flux values in the excised regions. Since the new fluxes in each region between indices `s` and `e` only depend on the neighbouring spectral points as
`modified_flux[i] = ws*flux[s] + we*flux[e]`
with the weights given by the relative distances to `wavelengths[[s,e]]`, technically the corresponding uncertainties `spectrum.uncertainty[i]` are given by
`np.sqrt(ws*spectrum.uncertainty[s]**2 + we*spectrum.uncertainty[e]**2)`
but those will all be correlated for the entire region, and should thus certainly not be used as a `StdDevUncertainty`.

3. Doing the above interpolation for the `flux` values with `np.linspace` implicitly assumes constant sampling of `spectral_axis`.

4. `excise_region` requires and checks for a `SpectralRegion` as `region` argument, but raises an error `'The region parameter must be a 2-tuples of start and end wavelengths.'` otherwise (probably left over from earlier versions where it did expect wavelength tuples).

**Comment by rosteen** [comment]
@nmearl I'm working on some code fixes/improvements in addition to correcting the docs for this. Should I make a new ticket for the new/improved functionality or can that live under this ticket?

Improvement-wise, I'm adding a true_exciser function that actually just removes the specified regions from the spectrum without replacement, and addressing a few of the concerns about the linear_exciser (updating the uncertainty as in (2) above and fixing the way it handles subregions).

**Comment by rosteen** [comment]
I'll also note that there didn't seem to be any test coverage for this functionality, so I'll be adding that as well.
