### ISSUE TITLE
does fit_lines use the uncertainties of the Spectrum when fitting?

### ISSUE THREAD

**Issue by andresgur** [astropy/specutils#505]
It seems to me that fit_lines does not use the uncertainties in the spectrum for the fitting. Is this correct? 

From the code:
`fit_model_unitless = fitter(model_unitless, dispersion_unitless, flux_unitless,
                                **kwargs)`
the uncertainties are not passed to the fitter as weights. Furthermore, fit_lines already has an argument called weights, so the uncertainties cannot even be passed to the fitter in the kwargs when calling `fit_lines` cause it recognises them as the argument for fit_lines, which has a different purpose.

**Comment by dhomeier** [comment]
`weights` is not implemented yet in `fit_lines` and will raise a `NotImplementedError` in `_fit_lines`, but once it is, you should certainly be able to pass something like `1/spectrum.uncertainties` to it, or am I missing something here? Of course if would be convenient to have a simple switch to directly take this from the `spectrum` argument.

**Comment by andresgur** [comment]
I thought weights is meant to be used to give weights to the regions you use in the fitting.
 From the docs:
"List of weights to define importance of fitting regions." 
that's what made me think that the library is missing the uncertainties in the fitting process...also because passing the uncertainties to the fitter requires pretty much the same coding effort as the current implementation. 
Maybe it's just a matter of time until it's added, of course

**Comment by dhomeier** [comment]
I was assuming the "list" was to be an array of weights for each spectral element, i.e. same shape as `spectrum.spectral_axis`, but you are right, it could also mean something like a list of `[weight, SpectralRegion]` pairs. No way to tell before it is actually added, but you could certainly implement it to accept both options, depending on the input type.
Might be worth a discussion whether there is interest to support such general `weights` vectors. Otherwise it could be easier to just handle the weights by region as you described, and use a separate keyword to enable weighting by uncertainties.

**Comment by dhomeier** [comment]
In fact the default `fitting.LevMarLSQFitter` (and almost all of the other `astropy.modeling` fitters) support a `weights` kwarg in the sense described above (an array of same shape as the data array, supposed to be 1/sigma for data with Gaussian uncertainties). In principle all that's needed is to have `_fit_lines` pass such a `weight` argument on to the fitter (just tested this, without using any `window` or `exclude_regions`, which would also need to be applied to this `weights` array).

**Comment by dhomeier** [comment]
I had to merge #490 to be able test this with astropy master. Otherwise the last person to have worked on this module seems to have been @brechmos-stsci - do you have any information on the timeline for adding the `weights` functionality?

**Comment by eteq** [comment]
@dhomeier  and @andresgur - to give a bit of backstory here - when `fit_lines` was first implemented we wanted to give the API a chance to go through it's paces before implementing uncertainties handling.  But this issue means now is the time to re-visit!

I think the most logical choice would be something like this:
1. If `weights` is None, don't use weights at all (i.e., equal weighting)
2. If `weights` is the special string 'unc' (or perhaps 'uncertainty'?), use `1/sigma` from the uncertainties.
3. If `weights` is array-like, pass it into the fitter otherwise un-altered.

Sounds reasonable?

**Comment by eteq** [comment]
Oh one caveat there: in *principle* fitters might have their own, different way of interpreting weights (i.e. inverse variance instread of inverse uncertainty).  I'm tempted to not worry too much about this because I think the syntax is generally consistent for most of the fitters and we can always special-case known outliers if we need to.  But it is a potential edge case trip-up to consider.

**Comment by nmearl** [comment]
The single string use case doesn't sit well with me, idiomatically. I think either we leave the `weights` argument up to the user entirely (i.e. `fit_lines(spectrum, model, weights=1/spectrum.uncertainties, ...)`, or expand the optional weights to include specific uncertainty transformations (e.g. `weights='std_dev'`, `weights='variance'`) that describe how to deal with the spectrum uncertainties.

**Comment by dhomeier** [comment]
I had thought about a similar scheme, but was sceptical about overloading the argument this way myself. But @nmearl's proposal sounds sensible in principle, although it seems that it will depend largely on the choice of `fitter` whether something else like 'variance' can or should be used for the `weights`.
Also, initially it appeared that taking `weights` directly from `spectrum.uncertainties` might be easier to implement, by directly using the `spectrum` already treated by the `window` and `exclude_regions` operations. But `_combined_region_data` does not return `uncertainties`, and `excise_regions` just keeps the original ones.

I find the logic behind the latter option difficult to follow anyway: Unlike suggested by the name `exclude_regions`, the modified spectrum returned by `excise_regions` still includes the full wavelength range with the respective regions replaced by linear interpolation between the neighbouring points. Their uncertainties could in principle be calculated from the uncertainties of those two spectral points, but they will all be highly correlated and certainly should not be used in place of standard deviations. And in any case the idea of fabricating such a linearly interpolated segment of the spectrum and then fitting a model to it seems odd.

**Comment by nmearl** [comment]
> But _combined_region_data does not return uncertainties, and excise_regions just keeps the original ones.

This might be a good discussion topic to open another issue for.

#511 now allows `weights` to be passed down to fitters in the `fit_lines` function.

**Comment by dhomeier** [comment]
> 
> This might be a good discussion topic to open another issue for.
> 
It's been mentioned in #496, but the entire topic how to treat the uncertainties probably warrants its own issue.

**Comment by be329** [comment]
Hello, 

Sorry if I have misunderstood, but when I am using weights='unc', my understanding is that it would take the uncertainties from the Spectrum1D object, which should be effectively a standard deviation, and pass that through to LevMarLSQFitter, which requires the weights as 1/sigma. 

Why, therefore, does _fit_lines do the following to find the weights, making them 1/sigma^2, not 1/sigma? 
 
`if isinstance(weights, str):
    if weights == 'unc':
        uncerts = spectrum.uncertainty

        if uncerts is not None:
            weights = uncerts.array ** -2`

**Comment by nmearl** [comment]
Hey @be329, we use `uncerts.array ** -2` due to, essentially, semantics. We're relating weights and uncertainties, and the form of the weights is dependent on the type of chi squared fitting used. In astropy, the chi squared is calculated as `sum(w * (predicted-model)**2)`, so the weights would need to be `w=uncertainty**-2` to keep units consistent.

**Comment by be329** [comment]
Hi @nmearl, thank you for replying. So just for my own understanding - it's not important that fit_lines calls LevMarLSQFitter, and that that function asks for the weights to be in the form of 1/sigma not 1/sigma^2? Sorry I'm a bit new to all of this!

**Comment by nmearl** [comment]
No need to apologize -- in fact, I think you're absolutely right; the weights _should_ be `uncerts.array ** -1`. I've opened a new issue [here](https://github.com/astropy/specutils/issues/587) to track this oversight. In the mean time, you're able to pass in your own weights to the `fit_lines` function instead of using the `unc` string, and those can simply be your inverse uncertainty objects.

**Comment by be329** [comment]
Oh ok fab, thank you for your help!
