### ISSUE TITLE
Check for continuum subtracted data

### ISSUE THREAD

**Issue by brechmos-stsci** [astropy/specutils#535]
Methods like `find_lines` needs to have data input that is already continuum subtracted otherwise the methods may not work.  
This method should then be added to `find_lines` methods and possibly others. 
Should this method throw an exception? Warning?

**Comment by brechmos-stsci** [comment]
There are a couple ways to check this, some slow and some fast:

 1. fit a continuum and see if it is very near 0 (probably too slow)
 2. could do a sigma clipping algorithm and then take the median (?) of what is left and see if it is near 0 (again, might be too slow)
 3. could just do a simple operation like mean or median to see how close it is to 0

**Comment by eteq** [comment]
Following a bit more discussion, here's a concrete proposal to start with:

1. Implement a function `guess_continuum_near_zero` that uses method 2 of @brechmos-stsci.
2. Implement a decorator `warn_if_continuum_near_zero` that can decorate analysis functions and generates a warning (with instructions on how to turn it off completely) that.
3. Do some profiling of the decorator on a test data set and `specutils.analysis.line_flux`, called repeatedly (perhaps ~10x times?). Use that to determine how much of a performance penalty there is vs not doing and use that to decide if method 3 or 1 might be more practical (or possibly other optimization tricks like caching the result in `meta`, although there be dragons there...)

**Comment by eteq** [comment]
Oh, but one clarification re: "method 2": if there is an uncertainty on the spectrum, instead of using the median and some tolerance, use flux divided by a standard-deviation-like uncertainty, and get the median of *that*. (basically per-pixel SNR, which is further motivation for #523 I guess.)

**Comment by brechmos-stsci** [comment]
And mask needs to be considered too.

**Comment by brechmos-stsci** [comment]
Umm... so... if we have a call structure of `is_continuum_near_zero(spectrum, eps)`  and we assume the spectrum has no mask nor uncertainty. What should the `eps` be?  For example, if flux is in Jy, that is going to be very different than if flux is in micro-Jy.  From an astronomy point of view, how would you determine if the continuum is near 0?  if the median is less than 0.1 Jy?  (I don't think that makes sense...).  Thoughts?

(I think I like `is_continuum_near_zero` rather than `guess_continuum_near_zero`, but that is an aside)

**Comment by eteq** [comment]
@brechmos-stsci ah, good point.  I think this is the options we want to consider for `eps`:
* If `eps` is a quantity (i.e. `hasattr(eps, 'unit')`, just do a direct comparison between the median of `spectrum.flux` and the `eps`.  
* If `eps` is a number (i.e.`not hasattr(eps, 'unit')`), do one of two things:
1. If `spectrum` has an uncertainty, do `median(spectrum.flux/spectrum.uncertainty)` (although it might need conversion to stddev type uncertainty?)
2. If `spectrum` does not have uncertainty, do `median(spectrum.flux)/astropy.stats.mad_std(spectrum.flux)`

I think that covers the cases of relevance here.

Re `is_continuum_near_zero` vs `guess_continuum_near_zero` - I'm not attached to `guess_continuum_near_zero` specifically, but I am not so sure about `is_continuum_near_zero` - the `is` to me implies "definitely is", whereas this function is more like "we think maybe it is, although for some spectra this might be deceptive".  E.g., a spectrum with a high fraction of spectral lines might actually fail this function because when you subtract the continuum there's still a fair amount of line flux left over. That's OK because it's an unusual case, but `guess` to me implies "this isn't quite as certain as something like asking whether it has an uncertainty".

**Comment by brechmos-stsci** [comment]
I think the 2. above is not quite right.  Let's say we have a `flux=[0.01, 0.0099, 0.011]*u.Jy`.  Then the `mad_std(flux) = 0.00148 Jy` and then the `np.median(flux) / mad_std(flux)` is `<Quantity 7.41938725>`.  So, I don't think we want to divide by any type of standard deviation.  If the flux data is close together then any type of standard deviation could be small.  But maybe I am not understanding something...

I think if there is no uncertainty, the flux has units and the eps does not have units, then maybe it should just throw an exception (?). But maybe there is a better solution.

**Comment by brechmos-stsci** [comment]
@eteq On the function name topic. I think the coding convention is to use "is" for methods that return True / False:
* https://stackoverflow.com/questions/47996388/python-boolean-methods-naming-convention
* https://stackoverflow.com/questions/1370840/naming-conventions-what-to-name-a-method-that-returns-a-boolean  (see highest voted answer)
So, I would suggest we keep the "is" but I can be convinced otherwise.

**Comment by eteq** [comment]
@brechmos-stsci  - right, I would agree that `is` is normally the right convention for booleans, but your first example is ``# some code that tests whether string is a palindrome``, which is a clear yes/no question.  In this case it's more like "returns a boolean for an *estimate* rather than a clear yes/no question".  But maybe that means something like `is_continuum_estimated_to_be_zero` ?

**Comment by brechmos-stsci** [comment]
Hmmm... not necessarily an estimate.  The `is` is if it is less than `eps`.  That is a clear yes or no.  
But, like said, others can decide on the name (not me).

**Comment by nmearl** [comment]
Perhaps the name can be changed to make it less ambiguous -- since `is_continuum_estimated_to_be_zero` is really just us asking "has this spectrum been continuum subtracted", why not call the function `is_continuum_subtracted`. Then there's less of a "guessing" nature, and it should be pretty unambiguously a yes/no question.

Now, personally, I have a strong preference for imperative verbs in function names vs indicative verbs, since indicative verbs _should_ really be paired with nouns: `spectrum_is_continuum_subtracted()`. This is *especially* true when the function is not a method (for, in the case where it _is_, the object instance acts as the subject noun: `my_spectral.is_continuum_subtracted()`).

With that said, I my preference would be to just remove the `is` entirely, and call the function `continuum_subtracted()`, or `continuum_near_zero()`.

**Comment by eteq** [comment]
On naming, @brechmos-stsci and I had an out-of-band conversation and came up with either `is_continuum_below_threshold` (or `continuum_below_threshold`) as something that captures more precisely what we're doing (and therefore doesn't have the "is"/"guess" problem I was concerned about).

Then to finalize the "is" question: I think with that wording, it's ambiguous what `continuum_below_threshold` returns because it could be returning the continuum rather than the answer to a question.  So I conclude `is_continuum_below_threshold` is the unambiguous choice because it can only return a yes/no question.


And to clarify re:
> since is_continuum_estimated_to_be_zero is really just us asking "has this spectrum been continuum subtracted", why not call the function is_continuum_subtracted

my point was that "running a function that subtracts a continuum" is *not* the same as what this function is checking.  Consider a poorly-fit continuum that is subtracted despite having a big offset. Then *a* continuum was subtracted, but the continuum is not near zero.  A more realistic science case is a spectrum where there's a lot of absorption covering at least half the spectrum.  Then the continuum might be subtracted but the average continuum level is not near zero. That's the "pathological" case, but it's the case where a user might say "why is it telling me I didn't subtract the continuum?  I *did*"

**Comment by eteq** [comment]
The first step of this is done in #538.  The project is not done given the description above, but it's probably better to just split this into follow-on issues.
