### ISSUE TITLE
Consider requiring passing astropy-dev job

### ISSUE THREAD

**Issue by bsipocz** [astropy/specutils#543]
Currently it's allowed to fail, and indeed is failing.  Consider fixing the issues and require it to pass as good practice (and provide feedback upstream if the issue is there and not here), otherwise there'll be bad surprises when the release is out.

**Comment by dhomeier** [comment]
Currently almost all of `fitting` is broken with Astropy 4.x; thought it was mainly due to stricter requirements on units usage, but there seem to be a couple of other issues with the `model` interface. Might take some time to fix, so for the time being I don't think passing with astropy-dev can really be made a requirement - any PR based on the current master will fail anyway.

**Comment by bsipocz** [comment]
Yes, that's the point. Before the end of the year the new release is out, and then it definitely will fail. And doing the fixes sooner rather than later could uncover issues with the refactored modeling in astropy, and frankly having that feedback before the release, preferably before the RC would be nice from a affiliated, let alone from coordinated package.

**Comment by dhomeier** [comment]
Looking back at my earlier tests, it seems #490 does address all the necessary changes, but has not been merged as it would in turn break compatibility with 3.2.

**Comment by dhomeier** [comment]
In that context, is there something like an official support roadmap for v0.6.x/v0.7, i.e. which releases shall be compatible with Astropy 4/backward compatible with 3.x and earlier; and which ones shall continue to support Python 3.5?
