### ISSUE TITLE
Default observer and target for SpectralCoord

### ISSUE THREAD

**Issue by astrofrog** [astropy/specutils#555]
*This is a spin-off discussion about one aspect of #524 which is not yet merged*

The purpose of this issue is to discuss what the default ``SpectralCoord`` ``observer`` and ``target`` should be.

### Option 1: have observer and target default to real coordinates

@eteq argued that these should  be set to something that isn't ``None`` , which is what is currently done in #524 (at the time of writing). The main reasons for this are:

* If we allowed ``observer`` and ``target`` to be ``None``, third-party code and user code interacting with ``SpectralCoord`` objects would need to special case the situation in which one or both of these properties are ``None``

* We don't need to special case things for computing radial velocities/redshifts

### Option 2: have observer and target default to None

On the other hand, I would argue that defaulting to something that isn't ``None`` could cause serious issues for users, and we should not allow operations that require an observer/target if these are not set. To see why defaulting to something that isn't None is a problem, let's say that we default to having the observer at the ICRS origin, and the target at (ra,dec)=(0,0).

A user defines a ``SpectralCoord`` for a target located at (ra,dec)=(0,90) but forgets to set the ``target`` or gets the ``SpectralCoord`` from a third-party function and doesn't realize the observer hasn't been set explicitly. The user also forgot to set the observer correctly - the observer is a spacecraft near the ICRS origin moving towards (ra,dec)=(0,0). The user now requests to transform the ``SpectralCoord`` to the solar system barycenter reference. Since the original observer and target were set (but not by the user), no warning happens, and the SpectralCoord values get corrected by the velocity of the spacecraft, even though the motion of the spacecraft was tangential to the direction of the source, so that in fact there should have been no correction effectively. User doesn't see any warnings or errors, and happily continues with their analysis.

Sometimes the observer and target aren't known, for example if creating a SpectralCoord from FITS headers, sometimes there is no information on observer and target. In my view, it's important that the user can get feedback about what they can and can't do without that information. For instance, they should be able to convert a frequency to wavelength, or a wavelength to a velocity in the radio convention assuming a rest wavelength/frequency. But they shouldn't be able to transform to a new observer without specifying both the original observer and the target.

One last note - I worry that just having warnings would not be enough - people disregard warnings all the time. For any operation that requires observer or target, we should in my view give a plain old error.

**Comment by hcferguson** [comment]
Interesting discussion....sort of comes down to when to irritate the user with niggling but possibly important details. 

For typical distant-galaxy work, high-precision redshifts and radial velocities aren't required. I wouldn't be thrilled with having a warning or error message if I'm just changing between z and heliocentric km/s. Not sure if your proposal, @astrofrog ,  would result in such an error message. 

On the other hand, one typically does worry about the reference frame when working with nearby galaxies and changing from heliocentric to LSR and at least having a warning would be good. I'm okay with an error if it provides short description of how to fix it.

I think I lean towards defaulting to None and requiring the applications to deal with that appropriately -- which might vary from application to application.

**Comment by nmearl** [comment]
I'm ambivalent (I had preferred the `None` approach, but I think I'm leaning more to the defaults approach). Here are my main issues with both approaches:
#### Against `None` approach
I don't particularly like that the `None` approach requires two ways to handle redshift/rv: the first, as consequences of an observer/target pair; and second, as raw values stored on the `SpectralCoord` object itself. It makes it ambiguous how setting a redshift/rv explicitly on a spectral coordinate that already has an observer/target is supposed to work -- conversely, how spectral coordinates are supposed to handle setting an observer/target that already has redshift/rv. It feels like a lot of introspection to handle all the cases. In the defaults approach, redshift/rv are only _consequences_ of an observer/target pair and are never raw values themselves, so there's only One Source of Truth for their value, and changing them requires changing the observer/target.

#### Against defaults approach
I don't like the idea of meaningless defaults, or defaults that can mislead the user. If I print my spectral coordinate object and see that the target and observer are at the center of the ICRS frame, what is that supposed to mean? How would I transform one or the other -- or would I need to reconstruct a spectral coordinate with a new pair? How does my data survive multiple transformations (e.g. if I transformed my observer to Keck _and then_ my target to Andromeda, is the data handled appropriately? The first step means that I'm at Keck looking at a target at the center of the ICRS frame.)

My alternative would be to create a dummy `BaseCoordinateFrame` class (perhaps inheriting from the ICRS frame), something like `UndefinedFrame` that can still allow us to implicitly handle/store redshift/rv values, but can also be recognized as something akin to `None` -- i.e. it won't have any allowed transforms to other frames, and the user has to explicitly set new observer/targets to do so.

**Comment by nmearl** [comment]
I'm coming to the conclusion that the default way is too cumbersome. There are quite a few edge cases that make having a consistent experience difficult.

1. No observer/target. This case is probably the simplest, but it raises a lot of questions. Mainly, it's trivial to create two empty ICRS frames and populate the target with the appropriate radial velocity provided by the user to store the difference in the frames. This is _fine_, but it requires making sure that the target is some distance from the observer, and that distance affects the transformation to any new target the user decides to look at.
2. Observer/no target. This one is tricky in that we have to create a target that is dependent on the frame of the observer. I.e. if the observer is at some position in the galactic frame, we can't simply make an empty ICRS frame for the target. I've tried copying the observer frame and setting a distance offset, but it's near impossible to override the values of a created frame without some frame-dependent code.
3. No observer/target. This is an annoying case where we have to be sure to set the differentials to ensure the calculations return the right sign.
4. Observer/target. Probably the easiest one because we just assume the user knows what they're doing and raise errors appropriately.

I'm getting to the point where I'd rather just not have to worry about the internal coordinate frames since they all seem to implement different available properties (i.e. `Galactic` does not expose `distance`, but it's still stored in it -- there are work-arounds, but they are specific to knowing the frame), and rely on the user to make whatever necessary changes themselves.

**Comment by astrofrog** [comment]
Note that we could still make it so that properties such as ``radial_velocity`` always work and just do different things internally depending on whether the observer/target are defined or not, and if we do that there may not be many other reasons for users to access observer and target individually.

**Comment by nmearl** [comment]
Agreed. That's what the current implementation does (PR #524).

**Comment by nmearl** [comment]
Since my [earlier comment](https://github.com/astropy/specutils/issues/555#issuecomment-562607878), I've revisited the implementation of the defaults case and found that some of the quirks were just a matter of not knowing enough of the coordinates machinery. Going ahead with exploring the defaults case again.

**Comment by eteq** [comment]
After some discussion I tried to capture in https://github.com/astropy/specutils/issues/422#issuecomment-591105322, @astrofrog, @nmearl, and I are now convinced by the argument that we need to allow the `None` case because sometimes the user wants to supply the `observer`/`target` after the fact, and/or downstream code needs to know "the user never specified anything definitively".

But @nmearl's concerns are somewhat assuaged by the idea that there's now only a few places that need to know about this internally (most importantly `in_velocity_frame`)

**Comment by nmearl** [comment]
This seems to have been addressed one way (in #619 and #674) and seems to be reversed in astropy/astropy#10400). Point being: it's _implemented_, and relevant discussions occurred/are occurring the appropriate issues/PRs.

**Comment by nmearl** [comment]
This seems to have been addressed one way (in #619 and #674) and seems to be reversed in astropy/astropy#10400). Point being: it's _implemented_, and relevant discussions occurred/are occurring the appropriate issues/PRs.

**Comment by nmearl** [comment]
This seems to have been addressed one way (in #619 and #674) and seems to be reversed in astropy/astropy#10400). Point being: it's _implemented_, and relevant discussions occurred/are occurring the appropriate issues/PRs.
