### ISSUE TITLE
Have `SpectralCoord` subclass and the spectrum objects consistently understand the concept of bin edges

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#626]
For some background relevant for this issue: a spectrum can be thought of in two different ways:
1. A "signal", where the signal is sampled at different points along the spectral axis, but the `flux` value is just "a sample of the signal"
2. "Flux in boxes" - e.g., the amount of energy (or number of photons) falling in one spectral "bin". 
Often this is functinonally very similar, but not always - see the flux conserving resampler for why it's sometimes critical to think like option 2. The OP of #176 also has a clear example of a science case where this is necessary.

For option 2, this means it's sometimes important to define a spectrum using bin *edges* rather than the current approach where `spectral_axis` is always aligned to the `flux`.  The most natural way to do this is to have `spectrum.spectral_axis.bin_edges` or possible `spectrum.spectral_axis_edges`.  Either way, the current `SpectralCoord` needs to be connected into this idea.

Some known pieces of this that should work:
1. For a spectrum created as the current `Spectrum1D` where the flux and `spectral_axis` are aligned, the "inner" bin edges should be the half-way point between two neighboring `spectral_axis` values.  The "outer" edges should be whatever makes the first and last bins be symmetric (i.e. for the first bin this means the left edge should be d/2 from the 0th spectral axis element where d is spectral_axis[1]-spectral_axis[0]).
2. There should also be a way to create a `Spectrum1D` where the bins are *explicitly* given (that's the need in #176) where the `spectral_axis` is then auto-created based on the middle-points of the bins.
3. The WCS should be such that the left-most bin edge is `spec.wcs.pixel_to_world(-0.5)`, the next bin edge is `spec.wcs.pixel_to_world(0.5)`, the next is `spec.wcs.pixel_to_world(1.5)` and so on.  (although see #494 - this might be to tall an order to start with, and could then be added later... @nmearl might have some insight).

Note also this issue is partly a roll-up of #176, #494, #495, and *possibly* #489, in that all of those are involved in a more consistent treatment of bin edges, which implementing in `SpectralCoord` would allow.

**Comment by astrofrog** [comment]
During in-person discussions, we decided that information about bin edges should not live on ``SpectralCoord`` (in the same way as image pixel edges shouldn't live on ``SkyCoord``), but instead that specutils could implement a ``SpectralAxis`` class that is a subclass of ``SpectralCoord`` that provides bin-related convenience properties.

**Comment by rosteen** [comment]
Good timing, I was just thinking about how best to add the bin properties to `SpectralCoord`. I'll start outlining `SpectralAxis` instead.

**Comment by nmearl** [comment]
@astrofrog The more I think about this the more I'm conflicted. It feels silly and excessive to have an entire subclass devoted to supporting `bin_edges`, but I can't seem to think of something else that would live in `SpectralAxis` that we would not want on `SpectralCoord`...

**Comment by astrofrog** [comment]
@eteq - very much separation of concerns - in reproject I might need a way to represent the corners of pixels in celestial coordinates but I think as an astropy.coordinates maintainer you would probably object to me adding ``SkyCoord.pixel_edges`` :) We should keep these things separate because they conceptually are separate. An example where bin edges don't make sense conceptually would be using ``SpectralCoord`` to represent the fitted peak frequency of a line in a spectrum, which may not line up with any pixel grid but still represents a physical spectral coordinate.

**Comment by astrofrog** [comment]
Perhaps a more general example, if in WCS I convert non-integer and non-contiguous pixel positions to world coordinates, then the resulting SpectralCoord will contain values that aren't on any grid and therefore bin edges wouldn't be relevant.

**Comment by eteq** [comment]
Yep, those are good examples, @astrofrog, and they convince me these are two separate things. 

It also makes me think one other thing: that maybe the subclass should actually be `SpectrumAxis` because that gets to the point that it's the spectral axis *of a spectrum*, as opposed to `SpectralCoord` which is a "coordinate of spectral type".  (This is admittedly getting deep into pedantry, but if there's one thing I can get behind it's that :wink:)

**Comment by nmearl** [comment]
Welp, can't argue with those examples. I'm onboard as well! 🙃

**Comment by rosteen** [comment]
I'm all for pedantry, however my preference would be to leave it as `SpectralAxis` rather than `SpectrumAxis`, because that leaves it nicely parallel to the `spectral_axis` parameter in `Spectrum1D`. I'd like the parameter and class to match up, and I think that not going through and changing the parameter everywhere is the less disruptive option, since users are already accustomed to using `spectral_axis`.

**Comment by nmearl** [comment]
@rosteen brings a good point. It's also less ambiguous to use `SpectralAxis` because it matches the general WCS specification of having a _spectral_ axis in relation to a _spatial_ axis. Likewise, `SpectrumAxis` as defined to be "an axis of a spectrum" could suggest something other than a spectral axis -- i.e. a 2D spectrum may have a spectral _and_ spatial axis, one could both axis types being the considered a "spectrum axis".

**Comment by perrygreenfield** [comment]
Could I ask a clarifying question? When you speak of bin edges is there a presumption that they align with the pixel coordinate or not? And if not, what use cases are being considered when not aligned with pixel coordinates?

**Comment by rosteen** [comment]
I have "known pieces" 1 and 2 from @eteq's original comment working, but #3 looks to be (as he said there) a thornier problem - mainly because `pec.wcs.pixel_to_world` doesn't seem to understand negative pixel values, so `pec.wcs.pixel_to_world(-0.5)` returns NaN rather than the first bin edge. How important is it to be able to retrieve the bin edges from the WCS rather than from `spec.bin_edges`?

One other note about the WCS is that in cases where the spectrum is initialized with bin edges that aren't regularly spaced (like in the nasty x-ray spectrum example in #176), the WCS won't recover any bin edges successfully from the bin edge centers, since (if I'm understanding correctly) it is using a linear fit of axis value vs. pixel number. I imagine that the user wouldn't care about the WCS in this case.

I need to write documentation, but I'll make a PR for this first so we can reference the code in further discussion.
