### ISSUE TITLE
Spectrum1D.read cannot auto-identify format of gzipped files

### ISSUE THREAD

**Issue by havok2063** [astropy/specutils#711]
The Spectrum1D.read method cannot auto-identify format of gzipped FITS files.  Spectrum1D can read in gzipped files ok when specifying the format keyword.  Without the format keyword, it throws an `OSError: Cannot read from/write to a closed file-like object (<gzip on 0x13234c6a0>).`  It probably has to do with getting the readable file object in `astropy.io.registry.read`.  Things fail when it gets inside the data loader method and tries to open the file a second time.  This issue might belong in the main `astropy` repo instead. 

To reproduce:
1. Download cube https://dr15.sdss.org/sas/dr15/manga/spectro/redux/v2_4_3/8485/stack/manga-8485-1901-LOGCUBE.fits.gz
2. Create an unzipped copy.  

```
from specutils import Spectrum1D

cube='/Users/bcherinka/Work/sdss/sas/dr15/manga/spectro/redux/v2_4_3/8485/stack/manga-8485-1901-LOGCUBE.fits.gz'
cube_unzip='/Users/bcherinka/Work/sdss/sas/dr15/manga/spectro/redux/v2_4_3/8485/stack/manga-8485-1901-LOGCUBE_unzip.fits'

# zipped fits fails 
s = Spectrum1D.read(cube)
...
OSError: Cannot read from/write to a closed file-like object (<gzip on 0x13234c130>).

# zipped fits reads correctly when specifying format
s = Spectrum1D.read(cube, format='MaNGA cube')
type(s)
specutils.spectra.spectrum1d.Spectrum1D

# unzipped fits correctly auto-identifies
s = Spectrum1D.read(cube_unzip)
type(s)
specutils.spectra.spectrum1d.Spectrum1D
```
To reproduce with existing loaders, you can download the file https://dr14.sdss.org/sas/dr14/eboss/spectro/redux/v5_10_0/spectra/lite/4055/spec-4055-55359-0596.fits, which is a `SDSS-III/IV spec` format and follow the same steps as above.  

Full traceback
```
s = Spectrum1d.read(cube)
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-36-3e77d30b6096> in <module>
----> 1 s=Spectrum1D.read(cube2)

~/anaconda3/envs/havokve/lib/python3.8/site-packages/astropy/nddata/mixins/ndio.py in __call__(self, *args, **kwargs)
     54
     55     def __call__(self, *args, **kwargs):
---> 56         return registry.read(self._cls, *args, **kwargs)
     57
     58

~/anaconda3/envs/havokve/lib/python3.8/site-packages/astropy/io/registry.py in read(cls, format, *args, **kwargs)
    528         print('format', format)
    529         reader = get_reader(format, cls)
--> 530         data = reader(*args, **kwargs)
    531         print('inside read')
    532         #breakpoint()

~/Work/git/havok2063/specutils/specutils/io/default_loaders/manga.py in manga_cube_loader(file_obj, **kwargs)
    126         hdulist = file_obj
    127     else:
--> 128         hdulist = fits.open(file_obj, **kwargs)
    129
    130     spaxel = u.Unit('spaxel', represents=u.pixel, doc='0.5" spatial pixel', parse_strict='silent')

~/anaconda3/envs/havokve/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py in fitsopen(name, mode, memmap, save_backup, cache, lazy_load_hdus, **kwargs)
    155         raise ValueError(f'Empty filename: {name!r}')
    156
--> 157     return HDUList.fromfile(name, mode, memmap, save_backup, cache,
    158                             lazy_load_hdus, **kwargs)
    159

~/anaconda3/envs/havokve/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py in fromfile(cls, fileobj, mode, memmap, save_backup, cache, lazy_load_hdus, **kwargs)
    393         """
    394
--> 395         return cls._readfrom(fileobj=fileobj, mode=mode, memmap=memmap,
    396                              save_backup=save_backup, cache=cache,
    397                              lazy_load_hdus=lazy_load_hdus, **kwargs)

~/anaconda3/envs/havokve/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py in _readfrom(cls, fileobj, data, mode, memmap, save_backup, cache, lazy_load_hdus, **kwargs)
   1044             if not isinstance(fileobj, _File):
   1045                 # instantiate a FITS file object (ffo)
-> 1046                 fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
   1047             # The Astropy mode is determined by the _File initializer if the
   1048             # supplied mode was None

~/anaconda3/envs/havokve/lib/python3.8/site-packages/astropy/utils/decorators.py in wrapper(*args, **kwargs)
    519                             kwargs[new_name[i]] = value
    520
--> 521             return function(*args, **kwargs)
    522
    523         return wrapper

~/anaconda3/envs/havokve/lib/python3.8/site-packages/astropy/io/fits/file.py in __init__(self, fileobj, mode, memmap, overwrite, cache)
    193             self._open_filename(fileobj, mode, overwrite)
    194         else:
--> 195             self._open_filelike(fileobj, mode, overwrite)
    196
    197         self.fileobj_mode = fileobj_mode(self._file)

~/anaconda3/envs/havokve/lib/python3.8/site-packages/astropy/io/fits/file.py in _open_filelike(self, fileobj, mode, overwrite)
    528
    529         if fileobj_closed(fileobj):
--> 530             raise OSError("Cannot read from/write to a closed file-like "
    531                           "object ({!r}).".format(fileobj))
    532

OSError: Cannot read from/write to a closed file-like object (<gzip on 0x13233c160>).
```

**Comment by dhomeier** [comment]
This _used_ to work (e.g. the `test_sdss_compressed` succeeded for both `gzip` and `bzip2` until some weeks ago).
I briefly suspected your new `_read_fileobj` contextmanager to be involved, but reproduced the problem now both with and without it, with astropy 4.0.1, 4.1rc[12] and 4.2dev.
The way `NDDataRead` and `registry.read` is involved here I agree with @eteq's suspicion in https://github.com/astropy/specutils/pull/717#issue-488427796 that it somehow is an upstream issue.

Since his patch in https://github.com/astropy/specutils/pull/717/commits/2cb3e1b78ea95f07bf87e3c9287630e5bcc6ca95 checking for `fits.util.fileobj_closed` does fix it for `gzip` and auto-detection _does_ work with

```
s = Spectrum1D.read(fits.open(cube))
```
I suspect that on calling the `identify_` function on the file name, `registry` somehow intercepts the  `fits.hdu.hdulist.HDUList` once opened, to continue its operations directly on the FITS handle, expecting it to remain open. This did not work since we wanted to make sure `identify_*` would not leave any open files behind. Beats me why the fix does not work on `bzip2` though...

**Comment by dhomeier** [comment]
OK, I got completely confused twice! It does work when resetting to pre-#702.

The problem is apparently that
https://github.com/astropy/specutils/blob/9ce88d6be700a06e888d9d0cdd04c0afc2ae85f8/specutils/io/parsing_utils.py#L27-L30

is always first trying to set `fileobj = args[2]`; with compressed files `registry` already passes `args[1:3]` as a tuple of (apparently opened) `bz2.BZ2File` or gzip `_io.FileIO` objects. So `fits.open` will open them, but not being `fits.HDUList`s they will then be closed before passing them over to the next identifier.

So a possible (tested locally) fix would be to revert to always using the filename in `args[0]` for anything but hdulists:
```
    if len(args) > 2 and isinstance(args[2], fits.HDUList):
        fileobj = args[2]
    else:
        fileobj = args[0]
```
(or integrating those checks into the `hdulist` reading).

Alternatively I guess one might extend the check in
https://github.com/astropy/specutils/blob/9ce88d6be700a06e888d9d0cdd04c0afc2ae85f8/specutils/io/parsing_utils.py#L41-L42

to all possible `bz2.BZ2File` etc. types – or _only_ ever close type `str` filenames (and `http.client.HTTPResponse` and the like...?). If you prefer direct access to the file handle...

**Comment by dhomeier** [comment]
OK, changing the cleanup in `read_fileobj_or_hdulist` to
```
    if not isinstance(fileobj, fits.hdu.hdulist.HDUList):
        try:
            fileobj.seek(0)
        except AttributeError:
            hdulist.close()
```
seems to do it as well. We probably should have a wider look at the state the different loaders leave the files in; there have been lots of `open_files=True` test failures before and still are.

**Comment by havok2063** [comment]
@dhomeier Thanks for looking into this and sorry for the caused problems.  #718 looks real nice!

**Comment by dhomeier** [comment]
I am sure using the context manager will be worth it by simplifying things a lot in the long run, so thanks again for contributing it!
