### ISSUE TITLE
logging directly to root conflicts with other package loggers

### ISSUE THREAD

**Issue by havok2063** [astropy/specutils#728]
Logging directly to the root , i.e.`logging.info` messes up the logging of packages that have `specutils` as  a dependency which use a named logger with its own stream handler.   Using `logging.info, etc` calls `logging.basicConfig`which creates a new StreamHandler at the top-level root logger, injecting itself as a parent to all other loggers.  This causes log messages to be displayed twice, once by the defined logger and again by the root.  There are certainly downstream (user-based) solutions to this, but it might be better to have `specutils` use a defined logger.

**Comment by rosteen** [comment]
FYI this is on my radar to fix. Looks like it might be as simple as using something like 
```
logger = logging.getLogger('specutils')
logger.warn("Whatever")
```
rather than using `logging.warn`, etc directly. A quick test shows that this results in
`WARNING:specutils: [...]`
rather than
`WARNING:root: [...]`

Does that seem sufficient to solve this, @havok2063 ? I'll just need to decide on the simplest way to apply this to the whole package, we don't need something as complex as the astropy logger class.

**Comment by pllim** [comment]
Hello. I got here from astropy/astropy#11600. I think this should completely be removed:

https://github.com/astropy/specutils/blob/57dd2b28e5122e00e28333043192d30ec9f78a9d/specutils/__init__.py#L55-L58

User should have some control of logging behavior, so it shouldn't be inside package init.

**Comment by saimn** [comment]
> User should have some control of logging behavior, so it shouldn't be inside package init.

If you want users to see messages by default there is not really another option than to setup the logger at import. But the problem here is that specutils uses the root logger to log messages, and apparently setup the root logger too late to display messages.

So instead specutils should
1. Use `logger = logging.getLogger(__name__) ; logger.warn/deug/etc.("Whatever")` in each module
2. Setup the "specutils" logger instead of the root one (`getLogger('specutils')`). Then people can still change it's level etc.

**Comment by pllim** [comment]
Incidentally, this behavior broke `synphot` testing locally. I have `specutils` installed and the test failed because it expected one warning but saw two. Uninstalling `specutils` fixed it. 😆

**Comment by havok2063** [comment]
It looks like my wish came true today!  🙏  @rosteen I think just creating a named logger for `specutils` as you suggest should work.  We just want to avoid its insertion into `log.root.handlers`.  I don't mind having a logger initialized in the package ``init`` as long as it doesn't demand it be the top dog log. 😉  .  I'd be happy to test any PR downstream.

**Comment by rosteen** [comment]
@havok2063 I created #810 to address this, your review would certainly be useful.
