### ISSUE TITLE
Implement moment method in spectrum data classes

### ISSUE THREAD

**Issue by rosteen** [astropy/specutils#745]
One can calculate the n-th moment of a cube with a simple call of `cube.moment(order=n)` in `spectral-cube` (see https://spectral-cube.readthedocs.io/en/latest/moments.html). We should add a method like this to appropriate spectrum objects as part of the `spectral-cube` transition to `specutils`.

**Comment by ibusko** [comment]
@rosteen do you envisage this as a method in the spectrum class (as is with spectral cube), or as a function similar to existing analysis and measurements functions in specutils? It seems to me, based on the current Spectrum1D API, that in specutils we moved away from having such kind of measurement functionality defined as  attributes of the spectrum object, instead having them being handled by functions. I ask because your wording above seems to imply otherwise. And there might be reasons for this that I am not aware of.

(this sort of touches on our discussion about the redshift slider)

**Comment by rosteen** [comment]
I was actually about to pull in @eteq for his thoughts on exactly this question on the `spectral_slab` PR, since I realized that in spectral cube that's attached to the cube object itself, as opposed to specutils having separate analysis functions (as you said Ivo). Following the rest of specutils by having it separate does conflict with "maximum back compatibility" with spectral cube, but I think that I'd personally default to the specutils convention of having it in the analysis functions rather than attached to the Spectrum1D. Thoughts @eteq ?

**Comment by nmearl** [comment]
I certainly think the precedent we've established for specutils should be maintained. That said, it might be worth using a proxy method with a deprecation decorator and plan to remove it in later releases:

```python
from ..manipulation import spectral_slab
from astropy.utils.decorators import deprecated


class Spectrum1D:
    ...
    @deprecated('0.2', alternative=':func:`~specutils.manipulation.spectral_slab.spectral_slab`', pending=False)
    def spectral_slab(self, *args, **kwargs):
        return spectral_slab(*args, **kwargs)
```

**Comment by ibusko** [comment]
@nmearl in principle it should work, but it leads to a circular import. `spectral_slab` imports Spectrum1D. This might require some revamping of the file and import structure in `specutils`. Unless there is a solution I'm not seeing right now.

**Comment by eteq** [comment]
Done in #758
