### ISSUE TITLE
Conserve shape of array when fitting a function to a sub region of the spectrum

### ISSUE THREAD

**Issue by ibusko** [astropy/specutils#760]
This came as a Developer Note in notebook https://spacetelescope.github.io/jdat_notebooks/jdat_notebooks/MRS_Mstar_analysis/JWST_Mstar_dataAnalysis_usecase.html  (cell 26)

The science case reported in the note is very specific: the user wants to approximate a region of the spectrum with a spline. So, even though the JIRA ticket (filed before the present github issue was filed) contains the term "fitting", I am assuming that the request does not apply to any kind of generic fitting, but instead applies to this narrower science case only. It seems to me that the requested operation would not make sense in cases where a physical spectrum model is being fitted to the data, since there seems to be no point in extending the fitted model with the original data, to the blue and/or red sides of the fitted model function.

**Comment by eteq** [comment]
(note there's some discussion in #762 about the best solution to this problem)

**Comment by PatrickOgle** [comment]
The title of this issue does not accurately describe the science case.  The corresponding PR (#762) should also be deprecated since it does something nonsensical from a science standpoint (resample a segment of the spectrum to a different wavelength grid while conserving the number of samples in that segment) .

I think what we want to do instead is this:
Create a spline-fitting function that replaces a segment of the input spectrum with the spline fit of that segment, maintaining the original wavelength sampling.
