### ISSUE TITLE
Find an example spectrum that's a bit more reliable for the docs

### ISSUE THREAD

**Issue by eteq** [astropy/specutils#773]
The SDSS spectrum at https://dr14.sdss.org/optical/spectrum/view/data/format=fits/spec=lite?plateid=1323&mjd=52797&fiberid=12 is used in several places in the specutils docs.  However, several times recently the server has been having issues and it messes up the doc builds when this happens.

I'd prefer if at all possible to avoid actually saving this somewhere in `specutils` or the `astropy` ecosystem, because we *want* to encourage users to use the original sources for archived data whenever possible. I asked @havok2063 about this and he suggested we use a URL that's on SAS (i.e. somewhere in e.g. https://data.sdss.org/sas/dr16/), as that may be a bit more reliable than the optical/spectrum may of accessing URLs.

To clarify: there's nothing special about that *particular* galaxy - I just went looking for an emission line galaxy because it's used to illustrate line-fitting.  But just about any starforming galaxy with a decent SDSS will do for this, and there are quite literally millions of them... I think part of the issue with this one is that it's from very early in the SDSS so it's not been processed by some of the later mechanisms - a galaxy from BOSS (a later stage of SDSS's spectroscopy) might be better because those seem to be a lot easier to find in SAS (the more reliable server).

cc @nmearl, who noticed it independently of me in #753

**Comment by havok2063** [comment]
Here is your original spectrum https://dr16.sdss.org/optical/spectrum/view?plateid=1323&mjd=52797&fiberid=12 and its location on the SAS https://data.sdss.org/sas/dr16/sdss/spectro/redux/26/spectra/1323/.   I don't know if you need something newer vs something more stable.  One option is to keep the object you have now but simply change the url you use to grab the spectrum.  The SAS url can be more stable than the API url, oddly.  There's no real need to change what spectrum is used since SDSS will always keep the old observations around.

**Comment by eteq** [comment]
Thanks @havok2063 ! I didn't realize this was still on the SAS - was thrown off by the "26" there!
