### ISSUE TITLE
FluxConservingResampler shouldn't be O(n^2)

### ISSUE THREAD

**Issue by sean-lockwood** [astropy/specutils#817]
I ran some timing measurements down-sampling a spectrum with the various resamplers, and found `FluxConservingResampler` quickly becomes unusable for output sampling > a few thousand points.
![FluxConservingResampler_timing](https://user-images.githubusercontent.com/5471441/116748063-d6607400-a9cc-11eb-8c6a-7941a486bc67.png)

For comparison, `LinearInterpolatedResampler` and `SplineInterpolatedResampler` scale well in the (larger) domain checked here (note units are `s` instead of `min`):
![resampler_timing](https://user-images.githubusercontent.com/5471441/116748118-f5f79c80-a9cc-11eb-9341-883d0555d013.png)

Since the output samples should be composable (at least with some overlap in the input range), I would expect the `FluxConservingResampler` algorithm to run in nearly linear time.  This algorithm is one of the main motivations for me to work with Specutils, so I hope we can improve its performance!

Computations run on a 2018 MacBook Pro 15" (2.9 GHz i9; 32GB RAM; OSX 10.15.7).

**Comment by eteq** [comment]
Revisiting this - I don't fully agree with @sean-lockwood here that it should be O(n), as the algorithm *in pinciple* could be O(n^2) since it's essentially a matrix operation, but in practice I agree it should be closer to O(n) than O(n^2) because the matrix should be nearly-diagonal.

More prosaically, if I try to resample a ~100k pixel spectrum onto a ~1k grid (a quite common operation for resampling models), it takes like a minute with `FluxConservingResampler`... but if I use `spectres` (https://github.com/ACCarnall/SpectRes), which is what the `FluxConservingResampler` is based on, it takes ~100 ms.

I think the core problem here is that `FluxConservingResampler` has implemented this as a naive matrix operation, which makes sense if you are directly implementing the formalism, but is computationally very inefficient for most real spectra because, again, most of the matrix elements are 0.  Fortunately, it seems we can use the `spectres` implementation to have a *much* faster approach, and we should probably either use it directly or indirectly.

**Comment by larrybradley** [comment]
@eteq Unfortunately, `SpecRes` has a GPLv3 license.

**Comment by pllim** [comment]
Fixed in #1060
