### ISSUE TITLE
TST: Mark remote data tests and doctests as remote data

### ISSUE THREAD

**Issue by pllim** [astropy/specutils#835]
https://github.com/astropy/specutils/pull/833#issuecomment-867105354

This is important to avoid all the jobs hammering service providers. Only one of the jobs should do it for any given push events.

* For test functions, use `@pytest.mark.remote_data` decorators.
* For doctest, use `# doctest: +REMOTE_DATA` at the end of each affected line. Support for code blocks will be available once astropy/pytest-doctestplus#137 is merged and released.

**Comment by dhomeier** [comment]
That would essentially involve adding `@pytest.mark.remote_data` to every `@remote_access` test?

Important because a number of the tests use fairly heavy downloads with plates or spectral cubes _O_(100 MB).

**Comment by pllim** [comment]
What is `@remote_access`? I never seen that decorator before.

**Comment by dhomeier** [comment]
It's pretty much all over the place in `test_loaders.py`. 😄
Looking at its definition
https://github.com/astropy/specutils/blob/3a86739d53663b528ee751eb55d01de3c252022d/specutils/tests/conftest.py#L16-L19
it looks actually like this should already skip them for `remote_data=False`; but what happens if the flag is not set at all (or rather, are there runs the do not set `remote_data` in any way)?

**Comment by pllim** [comment]
Errr... Why duplicate code? Why not just get rid of `remote_access` and use `remote_data`?

For doctest, you cannot use `@remote_data`, you need `pytest-remotedata` _and_ `pytest-doctestplus` to get `# doctest: +REMOTE_DATA` feature.

**Comment by pllim** [comment]
No, the Zenodo stuff you have to figure out, though in principle, I disagree on hiding it within a fixture like this, but I am not a maintainer here.

**Comment by dhomeier** [comment]
When first working on this it might be a bit puzzling where the data come from, but otherwise I don't have any particular issues with that.
But looking e.g. at the skips in `test_loaders` it seems evident that they are in fact skipped in all but the `CI / (Allowed Failure)` run, including those marked only`@remote_access`.

**Comment by pllim** [comment]
Okay, if you want to keep `remote_access`, that is fine, but someone has to go through all the doctest and mark remote data approrpiately.

**Comment by pllim** [comment]
I see REMOTE_DATA marked in docs now. Though I didn't verify if you caught it all. Good enough.
