### ISSUE TITLE
Your dev version is messing with my pinning

### ISSUE THREAD

**Issue by pllim** [astropy/specutils#858]
`jdaviz 1.2.dev532+ga7c177b requires specutils>=1.3, but you have specutils 1.3.dev139+g086c9aff which is incompatible`

As a result, the dev deps job is pulling in stable specutils instead of dev specutils. Can you please tell me how to fix this?

**Comment by rosteen** [comment]
I think what's going on here is that our `version.py` script uses `setuptools_scm`, which looks at the last tag and if there have been commits since then, iterates by a version and adds ".dev" (plus some other info). Since our last two releases have been off tags on the `v1.x` branch instead of `main`, the version is looking at the last tag on `main` (1.2) and saying that the version is 1.3.dev rather than 1.4.dev as it should. 

There's additionally a hard-coded fallback version there that currently matches what pip is reporting, but I checked and that's not getting triggered. 

Not sure what the best strategy here is, I'll think about it.

**Comment by rosteen** [comment]
I just manually tagged 1.4.dev on main, which should resolve the problem you're seeing. Could you kick off that test again and see if it's fixed?

**Comment by pllim** [comment]
Thanks! Let's see what the dev job says at https://github.com/spacetelescope/jdaviz/actions/runs/1210663081

**Comment by pllim** [comment]
p.s. For future reference, you want to tag next release dev at the commit right after the release. So this 1.4.dev tag is a bit inaccurate but not a deal break for me.

**Comment by rosteen** [comment]
I'm a tagging noob, not a connoisseur of well constructed tags - is there something wrong with that?

**Comment by pllim** [comment]
I think 1.4.dev should have started when 1.3.x got branched out. If you know when that was, I could possibly retag for you.

**Comment by pllim** [comment]
But if you want to leave it as-is, then you can close this issue. Thanks!
