### ISSUE TITLE
ERROR importing specutils: "ImportError: cannot import name 'SpectralCoord'"

### ISSUE THREAD

**Issue by jortiz12** [astropy/specutils#894]
Dear community, I´m having issues importing specutils (when a couple of weeks were not present).
Running basic import lines such as `from astropy.coordinates import SpectralCoord`
I get this error 
`ImportError: cannot import name 'SpectralCoord'`
It seems that is coming from this import
`from astropy.coordinates import SpectralCoord`

Any assistance would be much apprecited.
Kind Regard
Jose

**Comment by Yash-10** [comment]
Hello, @jortiz12 I think it is because `SpectralCoord` was added in v4.1 (see the note section here: https://docs.astropy.org/en/stable/api/astropy.coordinates.SpectralCoord.html) and this might error would occur if you would have an earlier version of astropy installed. Could you verify your astropy version?

```python
>>> import astropy
>>> astropy.__version__
'4.3.1'
```

(It seems `setup.cfg` was updated to use `astropy>=4.1`, so installing via the [instructions](https://specutils.readthedocs.io/en/stable/installation.html) might automatically install the latest astropy version).
