### ISSUE TITLE
FITS keyword comments not preserved by `tabular-fits` writer

### ISSUE THREAD

**Issue by kelle** [astropy/specutils#910]
FITS header keywords have three elements, a keyword name, a value, and a **_comment_**. In the following example, the comment (_target name_) is not preserved in the output FITS file.
```
header.set('OBJECT', test_object, 'target name')
spec.meta = header
spec.write(fits_filename, format ='tabular-fits', update_header=True)
```

The problem is somewhere in lines 120-126 of `tabular_fits.py`:
```
header = spectrum.meta.get('header', fits.header.Header()).copy()
if update_header:
        hdr_types = (str, int, float, complex, bool,
                     np.floating, np.integer, np.complexfloating, np.bool_)
        header.update([keyword for keyword in spectrum.meta.items() if
                       isinstance(keyword[1], hdr_types)])
```
I'm not familiar with `.update` method so I'm not quite sure how to fix it. But if someone points me in the right direction, I'm happy to try!

**Comment by dhomeier** [comment]
> header.update([keyword for keyword in spectrum.meta.items() if
>                        isinstance(keyword[1], hdr_types)])

Thanks for taking this on! That part might be solved (at least in preserving the header cards up to this point) with
```python
        header.update([keyword for keyword in fits.Header(spectrum.meta).cards if
                       isinstance(keyword[1], hdr_types)])
```
but generally this code is not even touched if the header is stored in `spectrum.meta['header']` (rather than having the individual cards directly in `meta`).
The header should in fact be passed intact to `Table.meta` at the end; I believe it is rather a shortcoming/"feature" of the `table` FITS writer to discard the comments on write. To be further investigated.
I any case it would not round trip, since the comments are currently inevitably discarded by `read_table_fits` (see discussion on [Slack#fits](https://astropy.slack.com/archives/C83KTJ2EM/p1632524138005900)).
So the whole issue lies mostly upstream with `astropy.table`, or would require bypassing its builtin `.write`/`.read` methods here.

**Comment by dhomeier** [comment]
Yes, similarly to above
https://github.com/astropy/astropy/blob/cd25e63293b621a92a9ffb5947203c6596391c02/astropy/io/fits/convenience.py#L599
would need to collect instead
```python
    for key, value, comment in table.meta.cards:
```

**Comment by kelle** [comment]
I've confirmed that the FITS keyword comments are preserved by the `tabular-fits` writer and it's `Table.write` that is discarding them. So this is an upstream issue. Fine with me to close this issue.
