### ISSUE TITLE
conda version

### ISSUE THREAD

**Issue by TheFinalDragon** [astropy/specutils#987]
I am using specutils from conda and the lastest conda package version has 1.7.0 version of specutils. I would like to use the 1.9.0 version, what is the best way of doing so? I am reluctant to work outside the conda package update system.

**Comment by rosteen** [comment]
Sorry about that - the outdated conda version is a known issue, our `conda-forge` builds are currently failing due to an error in an upstream dependency that has yet to be resolved. I would recommend doing a `pip install specutils` inside your activated conda environment in the meantime - while it would be nicer to have everything in the environment installed consistently with conda itself, I use this workflow all the time myself without problems.

**Comment by rosteen** [comment]
Hi @TheFinalDragon, specutils 1.9.1 is now available via conda. You may need to specify `--channel conda-forge` in the conda install command to ensure it picks up the most recent version.
